/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterAvailabilityZone } from './ClusterAvailabilityZone';
import {
    ClusterAvailabilityZoneFromJSON,
    ClusterAvailabilityZoneFromJSONTyped,
    ClusterAvailabilityZoneToJSON,
} from './ClusterAvailabilityZone';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 가용구역 복구계획
 * @export
 * @interface AvailabilityZoneRecoveryPlan
 */
export interface AvailabilityZoneRecoveryPlan {
    /**
     * 복구 유형 (매핑만 지원)
     * @type {string}
     * @memberof AvailabilityZoneRecoveryPlan
     */
    recovery_type_code?: AvailabilityZoneRecoveryPlanRecoveryTypeCodeEnum;
    /**
     * 
     * @type {ClusterAvailabilityZone}
     * @memberof AvailabilityZoneRecoveryPlan
     */
    protection_cluster_availability_zone?: ClusterAvailabilityZone;
    /**
     * 
     * @type {ClusterAvailabilityZone}
     * @memberof AvailabilityZoneRecoveryPlan
     */
    recovery_cluster_availability_zone?: ClusterAvailabilityZone;
    /**
     * 가용구역 변경 필요 여부
     * @type {boolean}
     * @memberof AvailabilityZoneRecoveryPlan
     */
    recovery_cluster_availability_zone_update_flag?: boolean;
    /**
     * 
     * @type {Message}
     * @memberof AvailabilityZoneRecoveryPlan
     */
    recovery_cluster_availability_zone_update_reason?: Message;
}


/**
 * @export
 */
export const AvailabilityZoneRecoveryPlanRecoveryTypeCodeEnum = {
    dr_recovery_plan_availability_zone_recovery_type_mapping: 'dr.recovery.plan.availability-zone.recovery.type.mapping'
} as const;
export type AvailabilityZoneRecoveryPlanRecoveryTypeCodeEnum = typeof AvailabilityZoneRecoveryPlanRecoveryTypeCodeEnum[keyof typeof AvailabilityZoneRecoveryPlanRecoveryTypeCodeEnum];


/**
 * Check if a given object implements the AvailabilityZoneRecoveryPlan interface.
 */
export function instanceOfAvailabilityZoneRecoveryPlan(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AvailabilityZoneRecoveryPlanFromJSON(json: any): AvailabilityZoneRecoveryPlan {
    return AvailabilityZoneRecoveryPlanFromJSONTyped(json, false);
}

export function AvailabilityZoneRecoveryPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailabilityZoneRecoveryPlan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recovery_type_code': !exists(json, 'recovery_type_code') ? undefined : json['recovery_type_code'],
        'protection_cluster_availability_zone': !exists(json, 'protection_cluster_availability_zone') ? undefined : ClusterAvailabilityZoneFromJSON(json['protection_cluster_availability_zone']),
        'recovery_cluster_availability_zone': !exists(json, 'recovery_cluster_availability_zone') ? undefined : ClusterAvailabilityZoneFromJSON(json['recovery_cluster_availability_zone']),
        'recovery_cluster_availability_zone_update_flag': !exists(json, 'recovery_cluster_availability_zone_update_flag') ? undefined : json['recovery_cluster_availability_zone_update_flag'],
        'recovery_cluster_availability_zone_update_reason': !exists(json, 'recovery_cluster_availability_zone_update_reason') ? undefined : MessageFromJSON(json['recovery_cluster_availability_zone_update_reason']),
    };
}

export function AvailabilityZoneRecoveryPlanToJSON(value?: AvailabilityZoneRecoveryPlan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recovery_type_code': value.recovery_type_code,
        'protection_cluster_availability_zone': ClusterAvailabilityZoneToJSON(value.protection_cluster_availability_zone),
        'recovery_cluster_availability_zone': ClusterAvailabilityZoneToJSON(value.recovery_cluster_availability_zone),
        'recovery_cluster_availability_zone_update_flag': value.recovery_cluster_availability_zone_update_flag,
        'recovery_cluster_availability_zone_update_reason': MessageToJSON(value.recovery_cluster_availability_zone_update_reason),
    };
}

