/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Cluster } from './Cluster';
import {
    ClusterFromJSON,
    ClusterFromJSONTyped,
    ClusterToJSON,
} from './Cluster';
import type { ClusterInstanceExtraSpec } from './ClusterInstanceExtraSpec';
import {
    ClusterInstanceExtraSpecFromJSON,
    ClusterInstanceExtraSpecFromJSONTyped,
    ClusterInstanceExtraSpecToJSON,
} from './ClusterInstanceExtraSpec';

/**
 * 클러스터 인스턴스 Specification
 * @export
 * @interface ClusterInstanceSpec
 */
export interface ClusterInstanceSpec {
    /**
     * Specification 의 ID
     * @type {number}
     * @memberof ClusterInstanceSpec
     */
    id?: number;
    /**
     * 
     * @type {Cluster}
     * @memberof ClusterInstanceSpec
     */
    cluster?: Cluster;
    /**
     * 클러스터에서의 Specification ID
     * @type {string}
     * @memberof ClusterInstanceSpec
     */
    uuid?: string;
    /**
     * Specification 의 이름
     * @type {string}
     * @memberof ClusterInstanceSpec
     */
    name?: string;
    /**
     * Specification 의 설명
     * @type {string}
     * @memberof ClusterInstanceSpec
     */
    description?: string;
    /**
     * VCPU 코어 수 (core)
     * @type {number}
     * @memberof ClusterInstanceSpec
     */
    vcpu_total_cnt?: number;
    /**
     * 메모리 용량 (bytes)
     * @type {number}
     * @memberof ClusterInstanceSpec
     */
    mem_total_bytes?: number;
    /**
     * 디스크 용량 (bytes)
     * @type {number}
     * @memberof ClusterInstanceSpec
     */
    disk_total_bytes?: number;
    /**
     * 스왑 영역 (bytes)
     * @type {number}
     * @memberof ClusterInstanceSpec
     */
    swap_total_bytes?: number;
    /**
     * 임시 영역 (bytes)
     * @type {number}
     * @memberof ClusterInstanceSpec
     */
    ephemeral_total_bytes?: number;
    /**
     * Extra Specifications
     * @type {Array<ClusterInstanceExtraSpec>}
     * @memberof ClusterInstanceSpec
     */
    extra_specs?: Array<ClusterInstanceExtraSpec>;
}

/**
 * Check if a given object implements the ClusterInstanceSpec interface.
 */
export function instanceOfClusterInstanceSpec(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterInstanceSpecFromJSON(json: any): ClusterInstanceSpec {
    return ClusterInstanceSpecFromJSONTyped(json, false);
}

export function ClusterInstanceSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterInstanceSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'cluster': !exists(json, 'cluster') ? undefined : ClusterFromJSON(json['cluster']),
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'vcpu_total_cnt': !exists(json, 'vcpu_total_cnt') ? undefined : json['vcpu_total_cnt'],
        'mem_total_bytes': !exists(json, 'mem_total_bytes') ? undefined : json['mem_total_bytes'],
        'disk_total_bytes': !exists(json, 'disk_total_bytes') ? undefined : json['disk_total_bytes'],
        'swap_total_bytes': !exists(json, 'swap_total_bytes') ? undefined : json['swap_total_bytes'],
        'ephemeral_total_bytes': !exists(json, 'ephemeral_total_bytes') ? undefined : json['ephemeral_total_bytes'],
        'extra_specs': !exists(json, 'extra_specs') ? undefined : ((json['extra_specs'] as Array<any>).map(ClusterInstanceExtraSpecFromJSON)),
    };
}

export function ClusterInstanceSpecToJSON(value?: ClusterInstanceSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'cluster': ClusterToJSON(value.cluster),
        'uuid': value.uuid,
        'name': value.name,
        'description': value.description,
        'vcpu_total_cnt': value.vcpu_total_cnt,
        'mem_total_bytes': value.mem_total_bytes,
        'disk_total_bytes': value.disk_total_bytes,
        'swap_total_bytes': value.swap_total_bytes,
        'ephemeral_total_bytes': value.ephemeral_total_bytes,
        'extra_specs': value.extra_specs === undefined ? undefined : ((value.extra_specs as Array<any>).map(ClusterInstanceExtraSpecToJSON)),
    };
}

