/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Cluster } from './Cluster';
import {
    ClusterFromJSON,
    ClusterFromJSONTyped,
    ClusterToJSON,
} from './Cluster';
import type { ClusterTenantQuota } from './ClusterTenantQuota';
import {
    ClusterTenantQuotaFromJSON,
    ClusterTenantQuotaFromJSONTyped,
    ClusterTenantQuotaToJSON,
} from './ClusterTenantQuota';

/**
 * 클러스터 테넌트
 * @export
 * @interface ClusterTenant
 */
export interface ClusterTenant {
    /**
     * 클러스터 테넌트의 ID
     * @type {number}
     * @memberof ClusterTenant
     */
    id?: number;
    /**
     * 
     * @type {Cluster}
     * @memberof ClusterTenant
     */
    cluster?: Cluster;
    /**
     * 클러스터에서의 테넌트 ID
     * @type {string}
     * @memberof ClusterTenant
     */
    uuid?: string;
    /**
     * 클러스터 테넌트의 이름
     * @type {string}
     * @memberof ClusterTenant
     */
    name?: string;
    /**
     * 클러스터 테넌트의 설명
     * @type {string}
     * @memberof ClusterTenant
     */
    description?: string;
    /**
     * 클러스터 테넌트 활성화 여부
     * @type {boolean}
     * @memberof ClusterTenant
     */
    enabled?: boolean;
    /**
     * 클러스터 테넌트 Quota 목록
     * @type {Array<ClusterTenantQuota>}
     * @memberof ClusterTenant
     */
    quotas?: Array<ClusterTenantQuota>;
}

/**
 * Check if a given object implements the ClusterTenant interface.
 */
export function instanceOfClusterTenant(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterTenantFromJSON(json: any): ClusterTenant {
    return ClusterTenantFromJSONTyped(json, false);
}

export function ClusterTenantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterTenant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'cluster': !exists(json, 'cluster') ? undefined : ClusterFromJSON(json['cluster']),
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'quotas': !exists(json, 'quotas') ? undefined : ((json['quotas'] as Array<any>).map(ClusterTenantQuotaFromJSON)),
    };
}

export function ClusterTenantToJSON(value?: ClusterTenant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'cluster': ClusterToJSON(value.cluster),
        'uuid': value.uuid,
        'name': value.name,
        'description': value.description,
        'enabled': value.enabled,
        'quotas': value.quotas === undefined ? undefined : ((value.quotas as Array<any>).map(ClusterTenantQuotaToJSON)),
    };
}

