/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Cluster } from './Cluster';
import {
    ClusterFromJSON,
    ClusterFromJSONTyped,
    ClusterToJSON,
} from './Cluster';
import type { ClusterTenant } from './ClusterTenant';
import {
    ClusterTenantFromJSON,
    ClusterTenantFromJSONTyped,
    ClusterTenantToJSON,
} from './ClusterTenant';

/**
 * 클러스터 보안그룹
 * @export
 * @interface ClusterSecurityGroup
 */
export interface ClusterSecurityGroup {
    /**
     * 클러스터 보안그룹의 ID
     * @type {number}
     * @memberof ClusterSecurityGroup
     */
    id?: number;
    /**
     * 
     * @type {Cluster}
     * @memberof ClusterSecurityGroup
     */
    cluster?: Cluster;
    /**
     * 
     * @type {ClusterTenant}
     * @memberof ClusterSecurityGroup
     */
    tenant?: ClusterTenant;
    /**
     * 클러스터에서의 보안그룹 ID
     * @type {string}
     * @memberof ClusterSecurityGroup
     */
    uuid?: string;
    /**
     * 클러스터 보안그룹의 이름
     * @type {string}
     * @memberof ClusterSecurityGroup
     */
    name?: string;
    /**
     * 클러스터 보안그룹의 설명
     * @type {string}
     * @memberof ClusterSecurityGroup
     */
    description?: string;
}

/**
 * Check if a given object implements the ClusterSecurityGroup interface.
 */
export function instanceOfClusterSecurityGroup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterSecurityGroupFromJSON(json: any): ClusterSecurityGroup {
    return ClusterSecurityGroupFromJSONTyped(json, false);
}

export function ClusterSecurityGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSecurityGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'cluster': !exists(json, 'cluster') ? undefined : ClusterFromJSON(json['cluster']),
        'tenant': !exists(json, 'tenant') ? undefined : ClusterTenantFromJSON(json['tenant']),
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ClusterSecurityGroupToJSON(value?: ClusterSecurityGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'cluster': ClusterToJSON(value.cluster),
        'tenant': ClusterTenantToJSON(value.tenant),
        'uuid': value.uuid,
        'name': value.name,
        'description': value.description,
    };
}

