/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AbnormalStateReasons } from './AbnormalStateReasons';
import {
    AbnormalStateReasonsFromJSON,
    AbnormalStateReasonsFromJSONTyped,
    AbnormalStateReasonsToJSON,
} from './AbnormalStateReasons';
import type { Cluster } from './Cluster';
import {
    ClusterFromJSON,
    ClusterFromJSONTyped,
    ClusterToJSON,
} from './Cluster';
import type { ProtectionGroup } from './ProtectionGroup';
import {
    ProtectionGroupFromJSON,
    ProtectionGroupFromJSONTyped,
    ProtectionGroupToJSON,
} from './ProtectionGroup';
import type { RecoveryPlanDetail } from './RecoveryPlanDetail';
import {
    RecoveryPlanDetailFromJSON,
    RecoveryPlanDetailFromJSONTyped,
    RecoveryPlanDetailToJSON,
} from './RecoveryPlanDetail';

/**
 * 
 * @export
 * @interface ClusterRelationshipPlansInner
 */
export interface ClusterRelationshipPlansInner {
    /**
     * 
     * @type {ProtectionGroup}
     * @memberof ClusterRelationshipPlansInner
     */
    group?: ProtectionGroup;
    /**
     * 재해복구계획 ID
     * @type {number}
     * @memberof ClusterRelationshipPlansInner
     */
    id?: number;
    /**
     * 
     * @type {Cluster}
     * @memberof ClusterRelationshipPlansInner
     */
    protection_cluster?: Cluster;
    /**
     * 
     * @type {Cluster}
     * @memberof ClusterRelationshipPlansInner
     */
    recovery_cluster?: Cluster;
    /**
     * 재해복구계획 이름
     * @type {string}
     * @memberof ClusterRelationshipPlansInner
     */
    name?: string;
    /**
     * 스냅샷 유지갯수
     * @type {number}
     * @memberof ClusterRelationshipPlansInner
     */
    snapshot_retention_count?: number;
    /**
     * 비고
     * @type {string}
     * @memberof ClusterRelationshipPlansInner
     */
    remarks?: string;
    /**
     * 복구 방향
     * @type {string}
     * @memberof ClusterRelationshipPlansInner
     */
    direction_code?: ClusterRelationshipPlansInnerDirectionCodeEnum;
    /**
     * 재해복구계획의 상태
     * @type {string}
     * @memberof ClusterRelationshipPlansInner
     */
    state_code?: ClusterRelationshipPlansInnerStateCodeEnum;
    /**
     * 
     * @type {AbnormalStateReasons}
     * @memberof ClusterRelationshipPlansInner
     */
    abnormal_state_reasons?: AbnormalStateReasons;
    /**
     * 재해복구계획 생성일시 (timestamp)
     * @type {number}
     * @memberof ClusterRelationshipPlansInner
     */
    created_at?: number;
    /**
     * 재해복구계획 최종 수정일시 (timestamp)
     * @type {number}
     * @memberof ClusterRelationshipPlansInner
     */
    updated_at?: number;
    /**
     * 
     * @type {RecoveryPlanDetail}
     * @memberof ClusterRelationshipPlansInner
     */
    detail?: RecoveryPlanDetail;
    /**
     * 수정가능 여부
     * @type {boolean}
     * @memberof ClusterRelationshipPlansInner
     */
    updatable?: boolean;
}


/**
 * @export
 */
export const ClusterRelationshipPlansInnerDirectionCodeEnum = {
    failover: 'dr.recovery.direction.failover',
    failback: 'dr.recovery.direction.failback'
} as const;
export type ClusterRelationshipPlansInnerDirectionCodeEnum = typeof ClusterRelationshipPlansInnerDirectionCodeEnum[keyof typeof ClusterRelationshipPlansInnerDirectionCodeEnum];

/**
 * @export
 */
export const ClusterRelationshipPlansInnerStateCodeEnum = {
    normal: 'dr.recovery.plan.state.normal',
    prepare: 'dr.recovery.plan.state.prepare',
    warning: 'dr.recovery.plan.state.warning',
    critical: 'dr.recovery.plan.state.critical',
    emergency: 'dr.recovery.plan.state.emergency'
} as const;
export type ClusterRelationshipPlansInnerStateCodeEnum = typeof ClusterRelationshipPlansInnerStateCodeEnum[keyof typeof ClusterRelationshipPlansInnerStateCodeEnum];


/**
 * Check if a given object implements the ClusterRelationshipPlansInner interface.
 */
export function instanceOfClusterRelationshipPlansInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterRelationshipPlansInnerFromJSON(json: any): ClusterRelationshipPlansInner {
    return ClusterRelationshipPlansInnerFromJSONTyped(json, false);
}

export function ClusterRelationshipPlansInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterRelationshipPlansInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': !exists(json, 'group') ? undefined : ProtectionGroupFromJSON(json['group']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'protection_cluster': !exists(json, 'protection_cluster') ? undefined : ClusterFromJSON(json['protection_cluster']),
        'recovery_cluster': !exists(json, 'recovery_cluster') ? undefined : ClusterFromJSON(json['recovery_cluster']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'snapshot_retention_count': !exists(json, 'snapshot_retention_count') ? undefined : json['snapshot_retention_count'],
        'remarks': !exists(json, 'remarks') ? undefined : json['remarks'],
        'direction_code': !exists(json, 'direction_code') ? undefined : json['direction_code'],
        'state_code': !exists(json, 'state_code') ? undefined : json['state_code'],
        'abnormal_state_reasons': !exists(json, 'abnormal_state_reasons') ? undefined : AbnormalStateReasonsFromJSON(json['abnormal_state_reasons']),
        'created_at': !exists(json, 'created_at') ? undefined : json['created_at'],
        'updated_at': !exists(json, 'updated_at') ? undefined : json['updated_at'],
        'detail': !exists(json, 'detail') ? undefined : RecoveryPlanDetailFromJSON(json['detail']),
        'updatable': !exists(json, 'updatable') ? undefined : json['updatable'],
    };
}

export function ClusterRelationshipPlansInnerToJSON(value?: ClusterRelationshipPlansInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': ProtectionGroupToJSON(value.group),
        'id': value.id,
        'protection_cluster': ClusterToJSON(value.protection_cluster),
        'recovery_cluster': ClusterToJSON(value.recovery_cluster),
        'name': value.name,
        'snapshot_retention_count': value.snapshot_retention_count,
        'remarks': value.remarks,
        'direction_code': value.direction_code,
        'state_code': value.state_code,
        'abnormal_state_reasons': AbnormalStateReasonsToJSON(value.abnormal_state_reasons),
        'created_at': value.created_at,
        'updated_at': value.updated_at,
        'detail': RecoveryPlanDetailToJSON(value.detail),
        'updatable': value.updatable,
    };
}

