/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 클러스터 네트워크 추가 라우트
 * @export
 * @interface ClusterRouterExtraRoute
 */
export interface ClusterRouterExtraRoute {
    /**
     * 클러스터 네트워크 라우트의 ID
     * @type {number}
     * @memberof ClusterRouterExtraRoute
     */
    id?: number;
    /**
     * 목적지 CIDR
     * @type {string}
     * @memberof ClusterRouterExtraRoute
     */
    destination?: string;
    /**
     * 목적지에 대한 Nexthop IP 주소
     * @type {string}
     * @memberof ClusterRouterExtraRoute
     */
    nexthop?: string;
}

/**
 * Check if a given object implements the ClusterRouterExtraRoute interface.
 */
export function instanceOfClusterRouterExtraRoute(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterRouterExtraRouteFromJSON(json: any): ClusterRouterExtraRoute {
    return ClusterRouterExtraRouteFromJSONTyped(json, false);
}

export function ClusterRouterExtraRouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterRouterExtraRoute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'destination': !exists(json, 'destination') ? undefined : json['destination'],
        'nexthop': !exists(json, 'nexthop') ? undefined : json['nexthop'],
    };
}

export function ClusterRouterExtraRouteToJSON(value?: ClusterRouterExtraRoute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'destination': value.destination,
        'nexthop': value.nexthop,
    };
}

