/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 클러스터 테넌트 Quota
 * @export
 * @interface ClusterTenantQuota
 */
export interface ClusterTenantQuota {
    /**
     * Quota Key
     * @type {string}
     * @memberof ClusterTenantQuota
     */
    key?: string;
    /**
     * Quota Value
     * @type {number}
     * @memberof ClusterTenantQuota
     */
    value?: number;
}

/**
 * Check if a given object implements the ClusterTenantQuota interface.
 */
export function instanceOfClusterTenantQuota(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterTenantQuotaFromJSON(json: any): ClusterTenantQuota {
    return ClusterTenantQuotaFromJSONTyped(json, false);
}

export function ClusterTenantQuotaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterTenantQuota {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ClusterTenantQuotaToJSON(value?: ClusterTenantQuota | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

