/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 클러스터 KeyPair
 * @export
 * @interface ClusterKeyPair
 */
export interface ClusterKeyPair {
    /**
     * KeyPair 의 ID
     * @type {number}
     * @memberof ClusterKeyPair
     */
    id?: number;
    /**
     * KeyPair 의 이름
     * @type {string}
     * @memberof ClusterKeyPair
     */
    name?: string;
    /**
     * KeyPair 의 fingerprint
     * @type {string}
     * @memberof ClusterKeyPair
     */
    fingerprint?: string;
    /**
     * KeyPair 의 public key
     * @type {string}
     * @memberof ClusterKeyPair
     */
    public_key?: string;
    /**
     * KeyPair 의 타입
     * @type {string}
     * @memberof ClusterKeyPair
     */
    type_code?: ClusterKeyPairTypeCodeEnum;
}


/**
 * @export
 */
export const ClusterKeyPairTypeCodeEnum = {
    ssh: 'ssh',
    x509: 'x509'
} as const;
export type ClusterKeyPairTypeCodeEnum = typeof ClusterKeyPairTypeCodeEnum[keyof typeof ClusterKeyPairTypeCodeEnum];


/**
 * Check if a given object implements the ClusterKeyPair interface.
 */
export function instanceOfClusterKeyPair(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterKeyPairFromJSON(json: any): ClusterKeyPair {
    return ClusterKeyPairFromJSONTyped(json, false);
}

export function ClusterKeyPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterKeyPair {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'fingerprint': !exists(json, 'fingerprint') ? undefined : json['fingerprint'],
        'public_key': !exists(json, 'public_key') ? undefined : json['public_key'],
        'type_code': !exists(json, 'type_code') ? undefined : json['type_code'],
    };
}

export function ClusterKeyPairToJSON(value?: ClusterKeyPair | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'fingerprint': value.fingerprint,
        'public_key': value.public_key,
        'type_code': value.type_code,
    };
}

