/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterFloatingIP } from './ClusterFloatingIP';
import {
    ClusterFloatingIPFromJSON,
    ClusterFloatingIPFromJSONTyped,
    ClusterFloatingIPToJSON,
} from './ClusterFloatingIP';
import type { ClusterNetwork } from './ClusterNetwork';
import {
    ClusterNetworkFromJSON,
    ClusterNetworkFromJSONTyped,
    ClusterNetworkToJSON,
} from './ClusterNetwork';
import type { ClusterSubnet } from './ClusterSubnet';
import {
    ClusterSubnetFromJSON,
    ClusterSubnetFromJSONTyped,
    ClusterSubnetToJSON,
} from './ClusterSubnet';

/**
 * 클러스터 인스턴스의 네트워크
 * @export
 * @interface ClusterInstanceNetwork
 */
export interface ClusterInstanceNetwork {
    /**
     * 인스턴스 네트워크의 ID
     * @type {number}
     * @memberof ClusterInstanceNetwork
     */
    id?: number;
    /**
     * 
     * @type {ClusterNetwork}
     * @memberof ClusterInstanceNetwork
     */
    network?: ClusterNetwork;
    /**
     * 
     * @type {ClusterSubnet}
     * @memberof ClusterInstanceNetwork
     */
    subnet?: ClusterSubnet;
    /**
     * 
     * @type {ClusterFloatingIP}
     * @memberof ClusterInstanceNetwork
     */
    floating_ip?: ClusterFloatingIP;
    /**
     * DHCP 여부
     * @type {boolean}
     * @memberof ClusterInstanceNetwork
     */
    dhcp_flag?: boolean;
    /**
     * IP 주소
     * @type {string}
     * @memberof ClusterInstanceNetwork
     */
    ip_address?: string;
}

/**
 * Check if a given object implements the ClusterInstanceNetwork interface.
 */
export function instanceOfClusterInstanceNetwork(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterInstanceNetworkFromJSON(json: any): ClusterInstanceNetwork {
    return ClusterInstanceNetworkFromJSONTyped(json, false);
}

export function ClusterInstanceNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterInstanceNetwork {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'network': !exists(json, 'network') ? undefined : ClusterNetworkFromJSON(json['network']),
        'subnet': !exists(json, 'subnet') ? undefined : ClusterSubnetFromJSON(json['subnet']),
        'floating_ip': !exists(json, 'floating_ip') ? undefined : ClusterFloatingIPFromJSON(json['floating_ip']),
        'dhcp_flag': !exists(json, 'dhcp_flag') ? undefined : json['dhcp_flag'],
        'ip_address': !exists(json, 'ip_address') ? undefined : json['ip_address'],
    };
}

export function ClusterInstanceNetworkToJSON(value?: ClusterInstanceNetwork | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'network': ClusterNetworkToJSON(value.network),
        'subnet': ClusterSubnetToJSON(value.subnet),
        'floating_ip': ClusterFloatingIPToJSON(value.floating_ip),
        'dhcp_flag': value.dhcp_flag,
        'ip_address': value.ip_address,
    };
}

