/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 클러스터 네트워크 서브넷의 DHCP Pool
 * @export
 * @interface ClusterSubnetDHCPPool
 */
export interface ClusterSubnetDHCPPool {
    /**
     * 클러스터 네트워크 서브넷 DHCP Pool 의 ID
     * @type {number}
     * @memberof ClusterSubnetDHCPPool
     */
    id?: number;
    /**
     * 할당 범위 시작 주소
     * @type {string}
     * @memberof ClusterSubnetDHCPPool
     */
    start_ip_address?: string;
    /**
     * 할당 범위 종료 주소
     * @type {string}
     * @memberof ClusterSubnetDHCPPool
     */
    end_ip_address?: string;
}

/**
 * Check if a given object implements the ClusterSubnetDHCPPool interface.
 */
export function instanceOfClusterSubnetDHCPPool(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClusterSubnetDHCPPoolFromJSON(json: any): ClusterSubnetDHCPPool {
    return ClusterSubnetDHCPPoolFromJSONTyped(json, false);
}

export function ClusterSubnetDHCPPoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSubnetDHCPPool {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'start_ip_address': !exists(json, 'start_ip_address') ? undefined : json['start_ip_address'],
        'end_ip_address': !exists(json, 'end_ip_address') ? undefined : json['end_ip_address'],
    };
}

export function ClusterSubnetDHCPPoolToJSON(value?: ClusterSubnetDHCPPool | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'start_ip_address': value.start_ip_address,
        'end_ip_address': value.end_ip_address,
    };
}

