/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterFloatingIP } from './ClusterFloatingIP';
import {
    ClusterFloatingIPFromJSON,
    ClusterFloatingIPFromJSONTyped,
    ClusterFloatingIPToJSON,
} from './ClusterFloatingIP';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * FloatingIP 복구계획
 * @export
 * @interface FloatingIPRecoveryPlan
 */
export interface FloatingIPRecoveryPlan {
    /**
     * 
     * @type {ClusterFloatingIP}
     * @memberof FloatingIPRecoveryPlan
     */
    protection_cluster_floating_ip?: ClusterFloatingIP;
    /**
     * 복구 불가 여부
     * @type {boolean}
     * @memberof FloatingIPRecoveryPlan
     */
    unavailable_flag?: boolean;
    /**
     * 
     * @type {Message}
     * @memberof FloatingIPRecoveryPlan
     */
    unavailable_reason?: Message;
}

/**
 * Check if a given object implements the FloatingIPRecoveryPlan interface.
 */
export function instanceOfFloatingIPRecoveryPlan(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FloatingIPRecoveryPlanFromJSON(json: any): FloatingIPRecoveryPlan {
    return FloatingIPRecoveryPlanFromJSONTyped(json, false);
}

export function FloatingIPRecoveryPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): FloatingIPRecoveryPlan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'protection_cluster_floating_ip': !exists(json, 'protection_cluster_floating_ip') ? undefined : ClusterFloatingIPFromJSON(json['protection_cluster_floating_ip']),
        'unavailable_flag': !exists(json, 'unavailable_flag') ? undefined : json['unavailable_flag'],
        'unavailable_reason': !exists(json, 'unavailable_reason') ? undefined : MessageFromJSON(json['unavailable_reason']),
    };
}

export function FloatingIPRecoveryPlanToJSON(value?: FloatingIPRecoveryPlan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'protection_cluster_floating_ip': ClusterFloatingIPToJSON(value.protection_cluster_floating_ip),
        'unavailable_flag': value.unavailable_flag,
        'unavailable_reason': MessageToJSON(value.unavailable_reason),
    };
}

