/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 의존하는 인스턴스
 * @export
 * @interface InstanceTemplateInstanceDependency
 */
export interface InstanceTemplateInstanceDependency {
    /**
     * 인스턴스 이름
     * @type {string}
     * @memberof InstanceTemplateInstanceDependency
     */
    name?: string;
}

/**
 * Check if a given object implements the InstanceTemplateInstanceDependency interface.
 */
export function instanceOfInstanceTemplateInstanceDependency(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InstanceTemplateInstanceDependencyFromJSON(json: any): InstanceTemplateInstanceDependency {
    return InstanceTemplateInstanceDependencyFromJSONTyped(json, false);
}

export function InstanceTemplateInstanceDependencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceTemplateInstanceDependency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function InstanceTemplateInstanceDependencyToJSON(value?: InstanceTemplateInstanceDependency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

