/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 보호그룹의 스냅샷
 * @export
 * @interface ProtectionGroupSnapshot
 */
export interface ProtectionGroupSnapshot {
    /**
     * 스냅샷 ID
     * @type {number}
     * @memberof ProtectionGroupSnapshot
     */
    id?: number;
    /**
     * 스냅샷 이름
     * @type {string}
     * @memberof ProtectionGroupSnapshot
     */
    name?: string;
    /**
     * 스냅샷 생성 일시
     * @type {number}
     * @memberof ProtectionGroupSnapshot
     */
    created_at?: number;
}

/**
 * Check if a given object implements the ProtectionGroupSnapshot interface.
 */
export function instanceOfProtectionGroupSnapshot(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProtectionGroupSnapshotFromJSON(json: any): ProtectionGroupSnapshot {
    return ProtectionGroupSnapshotFromJSONTyped(json, false);
}

export function ProtectionGroupSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtectionGroupSnapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'created_at': !exists(json, 'created_at') ? undefined : json['created_at'],
    };
}

export function ProtectionGroupSnapshotToJSON(value?: ProtectionGroupSnapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'created_at': value.created_at,
    };
}

