/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RecoveryJobInstanceStatus } from './RecoveryJobInstanceStatus';
import {
    RecoveryJobInstanceStatusFromJSON,
    RecoveryJobInstanceStatusFromJSONTyped,
    RecoveryJobInstanceStatusToJSON,
} from './RecoveryJobInstanceStatus';

/**
 * 
 * @export
 * @interface RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response
 */
export interface RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response {
    /**
     * 
     * @type {Array<RecoveryJobInstanceStatus>}
     * @memberof RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response
     */
    instances?: Array<RecoveryJobInstanceStatus>;
}

/**
 * Check if a given object implements the RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response interface.
 */
export function instanceOfRecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200ResponseFromJSON(json: any): RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response {
    return RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instances': !exists(json, 'instances') ? undefined : ((json['instances'] as Array<any>).map(RecoveryJobInstanceStatusFromJSON)),
    };
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200ResponseToJSON(value?: RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instances': value.instances === undefined ? undefined : ((value.instances as Array<any>).map(RecoveryJobInstanceStatusToJSON)),
    };
}

