/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterInstance } from './ClusterInstance';
import {
    ClusterInstanceFromJSON,
    ClusterInstanceFromJSONTyped,
    ClusterInstanceToJSON,
} from './ClusterInstance';
import type { ProtectionGroupSnapshot } from './ProtectionGroupSnapshot';
import {
    ProtectionGroupSnapshotFromJSON,
    ProtectionGroupSnapshotFromJSONTyped,
    ProtectionGroupSnapshotToJSON,
} from './ProtectionGroupSnapshot';

/**
 * 
 * @export
 * @interface RecoveryGroupsGroupIdJobsJobIdRetryPostRequest
 */
export interface RecoveryGroupsGroupIdJobsJobIdRetryPostRequest {
    /**
     * 데이터 시점 유형
     * @type {string}
     * @memberof RecoveryGroupsGroupIdJobsJobIdRetryPostRequest
     */
    recovery_point_type_code?: RecoveryGroupsGroupIdJobsJobIdRetryPostRequestRecoveryPointTypeCodeEnum;
    /**
     * 
     * @type {ProtectionGroupSnapshot}
     * @memberof RecoveryGroupsGroupIdJobsJobIdRetryPostRequest
     */
    recovery_point_snapshot?: ProtectionGroupSnapshot;
    /**
     * 재시도할 인스턴스 목록
     * @type {Array<ClusterInstance>}
     * @memberof RecoveryGroupsGroupIdJobsJobIdRetryPostRequest
     */
    instances?: Array<ClusterInstance>;
}


/**
 * @export
 */
export const RecoveryGroupsGroupIdJobsJobIdRetryPostRequestRecoveryPointTypeCodeEnum = {
    latest: 'dr.recovery.recovery_point.type.latest',
    latest_snapshot: 'dr.recovery.recovery_point.type.latest_snapshot',
    snapshot: 'dr.recovery.recovery_point.type.snapshot'
} as const;
export type RecoveryGroupsGroupIdJobsJobIdRetryPostRequestRecoveryPointTypeCodeEnum = typeof RecoveryGroupsGroupIdJobsJobIdRetryPostRequestRecoveryPointTypeCodeEnum[keyof typeof RecoveryGroupsGroupIdJobsJobIdRetryPostRequestRecoveryPointTypeCodeEnum];


/**
 * Check if a given object implements the RecoveryGroupsGroupIdJobsJobIdRetryPostRequest interface.
 */
export function instanceOfRecoveryGroupsGroupIdJobsJobIdRetryPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryGroupsGroupIdJobsJobIdRetryPostRequestFromJSON(json: any): RecoveryGroupsGroupIdJobsJobIdRetryPostRequest {
    return RecoveryGroupsGroupIdJobsJobIdRetryPostRequestFromJSONTyped(json, false);
}

export function RecoveryGroupsGroupIdJobsJobIdRetryPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryGroupsGroupIdJobsJobIdRetryPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recovery_point_type_code': !exists(json, 'recovery_point_type_code') ? undefined : json['recovery_point_type_code'],
        'recovery_point_snapshot': !exists(json, 'recovery_point_snapshot') ? undefined : ProtectionGroupSnapshotFromJSON(json['recovery_point_snapshot']),
        'instances': !exists(json, 'instances') ? undefined : ((json['instances'] as Array<any>).map(ClusterInstanceFromJSON)),
    };
}

export function RecoveryGroupsGroupIdJobsJobIdRetryPostRequestToJSON(value?: RecoveryGroupsGroupIdJobsJobIdRetryPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recovery_point_type_code': value.recovery_point_type_code,
        'recovery_point_snapshot': ProtectionGroupSnapshotToJSON(value.recovery_point_snapshot),
        'instances': value.instances === undefined ? undefined : ((value.instances as Array<any>).map(ClusterInstanceToJSON)),
    };
}

