/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceTemplate } from './InstanceTemplate';
import {
    InstanceTemplateFromJSON,
    InstanceTemplateFromJSONTyped,
    InstanceTemplateToJSON,
} from './InstanceTemplate';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 
 * @export
 * @interface RecoveryTemplatesPost201Response
 */
export interface RecoveryTemplatesPost201Response {
    /**
     * 
     * @type {InstanceTemplate}
     * @memberof RecoveryTemplatesPost201Response
     */
    instance_template?: InstanceTemplate;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryTemplatesPost201Response
     */
    message?: Message;
}

/**
 * Check if a given object implements the RecoveryTemplatesPost201Response interface.
 */
export function instanceOfRecoveryTemplatesPost201Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryTemplatesPost201ResponseFromJSON(json: any): RecoveryTemplatesPost201Response {
    return RecoveryTemplatesPost201ResponseFromJSONTyped(json, false);
}

export function RecoveryTemplatesPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryTemplatesPost201Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instance_template': !exists(json, 'instance_template') ? undefined : InstanceTemplateFromJSON(json['instance_template']),
        'message': !exists(json, 'message') ? undefined : MessageFromJSON(json['message']),
    };
}

export function RecoveryTemplatesPost201ResponseToJSON(value?: RecoveryTemplatesPost201Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instance_template': InstanceTemplateToJSON(value.instance_template),
        'message': MessageToJSON(value.message),
    };
}

