/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterSecurityGroup } from './ClusterSecurityGroup';
import {
    ClusterSecurityGroupFromJSON,
    ClusterSecurityGroupFromJSONTyped,
    ClusterSecurityGroupToJSON,
} from './ClusterSecurityGroup';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 보호그룹 복구 상태
 * @export
 * @interface RecoveryJobSecurityGroupStatus
 */
export interface RecoveryJobSecurityGroupStatus {
    /**
     * 
     * @type {ClusterSecurityGroup}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    security_group?: ClusterSecurityGroup;
    /**
     * 데이터 시점 유형
     * @type {string}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    recovery_point_type_code?: RecoveryJobSecurityGroupStatusRecoveryPointTypeCodeEnum;
    /**
     * 복구 데이터 시점
     * @type {number}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    recovery_point?: number;
    /**
     * 복구 시작 일시
     * @type {number}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    started_at?: number;
    /**
     * 복구 종료 일시
     * @type {number}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    finished_at?: number;
    /**
     * 복구 상태
     * @type {string}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    state_code?: RecoveryJobSecurityGroupStatusStateCodeEnum;
    /**
     * 복구 결과
     * @type {string}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    result_code?: RecoveryJobSecurityGroupStatusResultCodeEnum;
    /**
     * 복구, 롤백 상태
     * @type {string}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    type_code?: RecoveryJobSecurityGroupStatusTypeCodeEnum;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    failed_reason?: Message;
    /**
     * 롤백 여부
     * @type {boolean}
     * @memberof RecoveryJobSecurityGroupStatus
     */
    rollback_flag?: boolean;
}


/**
 * @export
 */
export const RecoveryJobSecurityGroupStatusRecoveryPointTypeCodeEnum = {
    latest: 'dr.recovery.recovery_point.type.latest',
    latest_snapshot: 'dr.recovery.recovery_point.type.latest_snapshot',
    snapshot: 'dr.recovery.recovery_point.type.snapshot'
} as const;
export type RecoveryJobSecurityGroupStatusRecoveryPointTypeCodeEnum = typeof RecoveryJobSecurityGroupStatusRecoveryPointTypeCodeEnum[keyof typeof RecoveryJobSecurityGroupStatusRecoveryPointTypeCodeEnum];

/**
 * @export
 */
export const RecoveryJobSecurityGroupStatusStateCodeEnum = {
    preparing: 'dr.recovery.job.security_group.state.preparing',
    excepted: 'dr.recovery.job.security_group.state.excepted',
    success: 'dr.recovery.job.security_group.state.success',
    failed: 'dr.recovery.job.security_group.state.failed'
} as const;
export type RecoveryJobSecurityGroupStatusStateCodeEnum = typeof RecoveryJobSecurityGroupStatusStateCodeEnum[keyof typeof RecoveryJobSecurityGroupStatusStateCodeEnum];

/**
 * @export
 */
export const RecoveryJobSecurityGroupStatusResultCodeEnum = {
    success: 'dr.recovery.security_group.result.success',
    failed: 'dr.recovery.security_group.result.failed',
    canceled: 'dr.recovery.security_group.result.canceled'
} as const;
export type RecoveryJobSecurityGroupStatusResultCodeEnum = typeof RecoveryJobSecurityGroupStatusResultCodeEnum[keyof typeof RecoveryJobSecurityGroupStatusResultCodeEnum];

/**
 * @export
 */
export const RecoveryJobSecurityGroupStatusTypeCodeEnum = {
    create: 'dr.migration.task.create',
    delete: 'dr.migration.task.delete'
} as const;
export type RecoveryJobSecurityGroupStatusTypeCodeEnum = typeof RecoveryJobSecurityGroupStatusTypeCodeEnum[keyof typeof RecoveryJobSecurityGroupStatusTypeCodeEnum];


/**
 * Check if a given object implements the RecoveryJobSecurityGroupStatus interface.
 */
export function instanceOfRecoveryJobSecurityGroupStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryJobSecurityGroupStatusFromJSON(json: any): RecoveryJobSecurityGroupStatus {
    return RecoveryJobSecurityGroupStatusFromJSONTyped(json, false);
}

export function RecoveryJobSecurityGroupStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryJobSecurityGroupStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'security_group': !exists(json, 'security_group') ? undefined : ClusterSecurityGroupFromJSON(json['security_group']),
        'recovery_point_type_code': !exists(json, 'recovery_point_type_code') ? undefined : json['recovery_point_type_code'],
        'recovery_point': !exists(json, 'recovery_point') ? undefined : json['recovery_point'],
        'started_at': !exists(json, 'started_at') ? undefined : json['started_at'],
        'finished_at': !exists(json, 'finished_at') ? undefined : json['finished_at'],
        'state_code': !exists(json, 'state_code') ? undefined : json['state_code'],
        'result_code': !exists(json, 'result_code') ? undefined : json['result_code'],
        'type_code': !exists(json, 'type_code') ? undefined : json['type_code'],
        'failed_reason': !exists(json, 'failed_reason') ? undefined : MessageFromJSON(json['failed_reason']),
        'rollback_flag': !exists(json, 'rollback_flag') ? undefined : json['rollback_flag'],
    };
}

export function RecoveryJobSecurityGroupStatusToJSON(value?: RecoveryJobSecurityGroupStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'security_group': ClusterSecurityGroupToJSON(value.security_group),
        'recovery_point_type_code': value.recovery_point_type_code,
        'recovery_point': value.recovery_point,
        'started_at': value.started_at,
        'finished_at': value.finished_at,
        'state_code': value.state_code,
        'result_code': value.result_code,
        'type_code': value.type_code,
        'failed_reason': MessageToJSON(value.failed_reason),
        'rollback_flag': value.rollback_flag,
    };
}

