/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { RecoveryDashboardSummaryClustersGet200ResponseSummary } from './RecoveryDashboardSummaryClustersGet200ResponseSummary';
import {
    RecoveryDashboardSummaryClustersGet200ResponseSummaryFromJSON,
    RecoveryDashboardSummaryClustersGet200ResponseSummaryFromJSONTyped,
    RecoveryDashboardSummaryClustersGet200ResponseSummaryToJSON,
} from './RecoveryDashboardSummaryClustersGet200ResponseSummary';

/**
 * 
 * @export
 * @interface RecoveryDashboardSummaryClustersGet200Response
 */
export interface RecoveryDashboardSummaryClustersGet200Response {
    /**
     * 
     * @type {RecoveryDashboardSummaryClustersGet200ResponseSummary}
     * @memberof RecoveryDashboardSummaryClustersGet200Response
     */
    summary?: RecoveryDashboardSummaryClustersGet200ResponseSummary;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryDashboardSummaryClustersGet200Response
     */
    message?: Message;
}

/**
 * Check if a given object implements the RecoveryDashboardSummaryClustersGet200Response interface.
 */
export function instanceOfRecoveryDashboardSummaryClustersGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardSummaryClustersGet200ResponseFromJSON(json: any): RecoveryDashboardSummaryClustersGet200Response {
    return RecoveryDashboardSummaryClustersGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryDashboardSummaryClustersGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardSummaryClustersGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'summary': !exists(json, 'summary') ? undefined : RecoveryDashboardSummaryClustersGet200ResponseSummaryFromJSON(json['summary']),
        'message': !exists(json, 'message') ? undefined : MessageFromJSON(json['message']),
    };
}

export function RecoveryDashboardSummaryClustersGet200ResponseToJSON(value?: RecoveryDashboardSummaryClustersGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'summary': RecoveryDashboardSummaryClustersGet200ResponseSummaryToJSON(value.summary),
        'message': MessageToJSON(value.message),
    };
}

