/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterInstance } from './ClusterInstance';
import {
    ClusterInstanceFromJSON,
    ClusterInstanceFromJSONTyped,
    ClusterInstanceToJSON,
} from './ClusterInstance';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 
 * @export
 * @interface RecoveryGroupsGroupIdJobsPost412ResponseInstancesInner
 */
export interface RecoveryGroupsGroupIdJobsPost412ResponseInstancesInner {
    /**
     * 
     * @type {ClusterInstance}
     * @memberof RecoveryGroupsGroupIdJobsPost412ResponseInstancesInner
     */
    instance?: ClusterInstance;
    /**
     * 
     * @type {Array<Message>}
     * @memberof RecoveryGroupsGroupIdJobsPost412ResponseInstancesInner
     */
    unavailable_reasons?: Array<Message>;
}

/**
 * Check if a given object implements the RecoveryGroupsGroupIdJobsPost412ResponseInstancesInner interface.
 */
export function instanceOfRecoveryGroupsGroupIdJobsPost412ResponseInstancesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryGroupsGroupIdJobsPost412ResponseInstancesInnerFromJSON(json: any): RecoveryGroupsGroupIdJobsPost412ResponseInstancesInner {
    return RecoveryGroupsGroupIdJobsPost412ResponseInstancesInnerFromJSONTyped(json, false);
}

export function RecoveryGroupsGroupIdJobsPost412ResponseInstancesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryGroupsGroupIdJobsPost412ResponseInstancesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instance': !exists(json, 'instance') ? undefined : ClusterInstanceFromJSON(json['instance']),
        'unavailable_reasons': !exists(json, 'unavailable_reasons') ? undefined : ((json['unavailable_reasons'] as Array<any>).map(MessageFromJSON)),
    };
}

export function RecoveryGroupsGroupIdJobsPost412ResponseInstancesInnerToJSON(value?: RecoveryGroupsGroupIdJobsPost412ResponseInstancesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instance': ClusterInstanceToJSON(value.instance),
        'unavailable_reasons': value.unavailable_reasons === undefined ? undefined : ((value.unavailable_reasons as Array<any>).map(MessageToJSON)),
    };
}

