/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterSubnet } from './ClusterSubnet';
import {
    ClusterSubnetFromJSON,
    ClusterSubnetFromJSONTyped,
    ClusterSubnetToJSON,
} from './ClusterSubnet';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 서브넷 복구 상태
 * @export
 * @interface RecoveryJobSubnetStatus
 */
export interface RecoveryJobSubnetStatus {
    /**
     * 
     * @type {ClusterSubnet}
     * @memberof RecoveryJobSubnetStatus
     */
    subnet?: ClusterSubnet;
    /**
     * 데이터 시점 유형
     * @type {string}
     * @memberof RecoveryJobSubnetStatus
     */
    recovery_point_type_code?: RecoveryJobSubnetStatusRecoveryPointTypeCodeEnum;
    /**
     * 복구 데이터 시점
     * @type {number}
     * @memberof RecoveryJobSubnetStatus
     */
    recovery_point?: number;
    /**
     * 복구 시작 일시
     * @type {number}
     * @memberof RecoveryJobSubnetStatus
     */
    started_at?: number;
    /**
     * 복구 종료 일시
     * @type {number}
     * @memberof RecoveryJobSubnetStatus
     */
    finished_at?: number;
    /**
     * 복구 상태
     * @type {string}
     * @memberof RecoveryJobSubnetStatus
     */
    state_code?: RecoveryJobSubnetStatusStateCodeEnum;
    /**
     * 복구 결과
     * @type {string}
     * @memberof RecoveryJobSubnetStatus
     */
    result_code?: RecoveryJobSubnetStatusResultCodeEnum;
    /**
     * 복구, 롤백 상태
     * @type {string}
     * @memberof RecoveryJobSubnetStatus
     */
    type_code?: RecoveryJobSubnetStatusTypeCodeEnum;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryJobSubnetStatus
     */
    failed_reason?: Message;
    /**
     * 롤백 여부
     * @type {boolean}
     * @memberof RecoveryJobSubnetStatus
     */
    rollback_flag?: boolean;
}


/**
 * @export
 */
export const RecoveryJobSubnetStatusRecoveryPointTypeCodeEnum = {
    latest: 'dr.recovery.recovery_point.type.latest',
    latest_snapshot: 'dr.recovery.recovery_point.type.latest_snapshot',
    snapshot: 'dr.recovery.recovery_point.type.snapshot'
} as const;
export type RecoveryJobSubnetStatusRecoveryPointTypeCodeEnum = typeof RecoveryJobSubnetStatusRecoveryPointTypeCodeEnum[keyof typeof RecoveryJobSubnetStatusRecoveryPointTypeCodeEnum];

/**
 * @export
 */
export const RecoveryJobSubnetStatusStateCodeEnum = {
    waiting: 'waiting',
    running: 'running',
    done: 'done'
} as const;
export type RecoveryJobSubnetStatusStateCodeEnum = typeof RecoveryJobSubnetStatusStateCodeEnum[keyof typeof RecoveryJobSubnetStatusStateCodeEnum];

/**
 * @export
 */
export const RecoveryJobSubnetStatusResultCodeEnum = {
    success: 'success',
    failed: 'failed',
    excepted: 'excepted',
    ignored: 'ignored',
    canceled: 'canceled'
} as const;
export type RecoveryJobSubnetStatusResultCodeEnum = typeof RecoveryJobSubnetStatusResultCodeEnum[keyof typeof RecoveryJobSubnetStatusResultCodeEnum];

/**
 * @export
 */
export const RecoveryJobSubnetStatusTypeCodeEnum = {
    create: 'dr.migration.task.create',
    delete: 'dr.migration.task.delete'
} as const;
export type RecoveryJobSubnetStatusTypeCodeEnum = typeof RecoveryJobSubnetStatusTypeCodeEnum[keyof typeof RecoveryJobSubnetStatusTypeCodeEnum];


/**
 * Check if a given object implements the RecoveryJobSubnetStatus interface.
 */
export function instanceOfRecoveryJobSubnetStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryJobSubnetStatusFromJSON(json: any): RecoveryJobSubnetStatus {
    return RecoveryJobSubnetStatusFromJSONTyped(json, false);
}

export function RecoveryJobSubnetStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryJobSubnetStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subnet': !exists(json, 'subnet') ? undefined : ClusterSubnetFromJSON(json['subnet']),
        'recovery_point_type_code': !exists(json, 'recovery_point_type_code') ? undefined : json['recovery_point_type_code'],
        'recovery_point': !exists(json, 'recovery_point') ? undefined : json['recovery_point'],
        'started_at': !exists(json, 'started_at') ? undefined : json['started_at'],
        'finished_at': !exists(json, 'finished_at') ? undefined : json['finished_at'],
        'state_code': !exists(json, 'state_code') ? undefined : json['state_code'],
        'result_code': !exists(json, 'result_code') ? undefined : json['result_code'],
        'type_code': !exists(json, 'type_code') ? undefined : json['type_code'],
        'failed_reason': !exists(json, 'failed_reason') ? undefined : MessageFromJSON(json['failed_reason']),
        'rollback_flag': !exists(json, 'rollback_flag') ? undefined : json['rollback_flag'],
    };
}

export function RecoveryJobSubnetStatusToJSON(value?: RecoveryJobSubnetStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subnet': ClusterSubnetToJSON(value.subnet),
        'recovery_point_type_code': value.recovery_point_type_code,
        'recovery_point': value.recovery_point,
        'started_at': value.started_at,
        'finished_at': value.finished_at,
        'state_code': value.state_code,
        'result_code': value.result_code,
        'type_code': value.type_code,
        'failed_reason': MessageToJSON(value.failed_reason),
        'rollback_flag': value.rollback_flag,
    };
}

