/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { RecoveryDashboardSummaryVolumesGet200ResponseSummary } from './RecoveryDashboardSummaryVolumesGet200ResponseSummary';
import {
    RecoveryDashboardSummaryVolumesGet200ResponseSummaryFromJSON,
    RecoveryDashboardSummaryVolumesGet200ResponseSummaryFromJSONTyped,
    RecoveryDashboardSummaryVolumesGet200ResponseSummaryToJSON,
} from './RecoveryDashboardSummaryVolumesGet200ResponseSummary';

/**
 * 
 * @export
 * @interface RecoveryDashboardSummaryVolumesGet200Response
 */
export interface RecoveryDashboardSummaryVolumesGet200Response {
    /**
     * 
     * @type {RecoveryDashboardSummaryVolumesGet200ResponseSummary}
     * @memberof RecoveryDashboardSummaryVolumesGet200Response
     */
    summary?: RecoveryDashboardSummaryVolumesGet200ResponseSummary;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryDashboardSummaryVolumesGet200Response
     */
    message?: Message;
}

/**
 * Check if a given object implements the RecoveryDashboardSummaryVolumesGet200Response interface.
 */
export function instanceOfRecoveryDashboardSummaryVolumesGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardSummaryVolumesGet200ResponseFromJSON(json: any): RecoveryDashboardSummaryVolumesGet200Response {
    return RecoveryDashboardSummaryVolumesGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryDashboardSummaryVolumesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardSummaryVolumesGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'summary': !exists(json, 'summary') ? undefined : RecoveryDashboardSummaryVolumesGet200ResponseSummaryFromJSON(json['summary']),
        'message': !exists(json, 'message') ? undefined : MessageFromJSON(json['message']),
    };
}

export function RecoveryDashboardSummaryVolumesGet200ResponseToJSON(value?: RecoveryDashboardSummaryVolumesGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'summary': RecoveryDashboardSummaryVolumesGet200ResponseSummaryToJSON(value.summary),
        'message': MessageToJSON(value.message),
    };
}

