/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { RecoveryResult } from './RecoveryResult';
import {
    RecoveryResultFromJSON,
    RecoveryResultFromJSONTyped,
    RecoveryResultToJSON,
} from './RecoveryResult';

/**
 * 
 * @export
 * @interface RecoveryHistoryGroupIdReportsResultIdDetailGet200Response
 */
export interface RecoveryHistoryGroupIdReportsResultIdDetailGet200Response {
    /**
     * 
     * @type {RecoveryResult}
     * @memberof RecoveryHistoryGroupIdReportsResultIdDetailGet200Response
     */
    report?: RecoveryResult;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryHistoryGroupIdReportsResultIdDetailGet200Response
     */
    message?: Message;
}

/**
 * Check if a given object implements the RecoveryHistoryGroupIdReportsResultIdDetailGet200Response interface.
 */
export function instanceOfRecoveryHistoryGroupIdReportsResultIdDetailGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryHistoryGroupIdReportsResultIdDetailGet200ResponseFromJSON(json: any): RecoveryHistoryGroupIdReportsResultIdDetailGet200Response {
    return RecoveryHistoryGroupIdReportsResultIdDetailGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryHistoryGroupIdReportsResultIdDetailGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryHistoryGroupIdReportsResultIdDetailGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'report': !exists(json, 'report') ? undefined : RecoveryResultFromJSON(json['report']),
        'message': !exists(json, 'message') ? undefined : MessageFromJSON(json['message']),
    };
}

export function RecoveryHistoryGroupIdReportsResultIdDetailGet200ResponseToJSON(value?: RecoveryHistoryGroupIdReportsResultIdDetailGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'report': RecoveryResultToJSON(value.report),
        'message': MessageToJSON(value.message),
    };
}

