/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecoveryDashboardSummaryClustersGet200ResponseSummary
 */
export interface RecoveryDashboardSummaryClustersGet200ResponseSummary {
    /**
     * 모든 클러스터 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryClustersGet200ResponseSummary
     */
    total_cluster?: number;
    /**
     * 활성화 클러스터 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryClustersGet200ResponseSummary
     */
    active_cluster?: number;
    /**
     * 비활성화 클러스터 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryClustersGet200ResponseSummary
     */
    inactive_cluster?: number;
}

/**
 * Check if a given object implements the RecoveryDashboardSummaryClustersGet200ResponseSummary interface.
 */
export function instanceOfRecoveryDashboardSummaryClustersGet200ResponseSummary(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardSummaryClustersGet200ResponseSummaryFromJSON(json: any): RecoveryDashboardSummaryClustersGet200ResponseSummary {
    return RecoveryDashboardSummaryClustersGet200ResponseSummaryFromJSONTyped(json, false);
}

export function RecoveryDashboardSummaryClustersGet200ResponseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardSummaryClustersGet200ResponseSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total_cluster': !exists(json, 'total_cluster') ? undefined : json['total_cluster'],
        'active_cluster': !exists(json, 'active_cluster') ? undefined : json['active_cluster'],
        'inactive_cluster': !exists(json, 'inactive_cluster') ? undefined : json['inactive_cluster'],
    };
}

export function RecoveryDashboardSummaryClustersGet200ResponseSummaryToJSON(value?: RecoveryDashboardSummaryClustersGet200ResponseSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_cluster': value.total_cluster,
        'active_cluster': value.active_cluster,
        'inactive_cluster': value.inactive_cluster,
    };
}

