/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterKeyPair } from './ClusterKeyPair';
import {
    ClusterKeyPairFromJSON,
    ClusterKeyPairFromJSONTyped,
    ClusterKeyPairToJSON,
} from './ClusterKeyPair';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 키페어 복구 상태
 * @export
 * @interface RecoveryJobKeyPairStatus
 */
export interface RecoveryJobKeyPairStatus {
    /**
     * 
     * @type {ClusterKeyPair}
     * @memberof RecoveryJobKeyPairStatus
     */
    keypair?: ClusterKeyPair;
    /**
     * 데이터 시점 유형
     * @type {string}
     * @memberof RecoveryJobKeyPairStatus
     */
    recovery_point_type_code?: RecoveryJobKeyPairStatusRecoveryPointTypeCodeEnum;
    /**
     * 복구 데이터 시점
     * @type {number}
     * @memberof RecoveryJobKeyPairStatus
     */
    recovery_point?: number;
    /**
     * 복구 시작 일시
     * @type {number}
     * @memberof RecoveryJobKeyPairStatus
     */
    started_at?: number;
    /**
     * 복구 종료 일시
     * @type {number}
     * @memberof RecoveryJobKeyPairStatus
     */
    finished_at?: number;
    /**
     * 복구 상태
     * @type {string}
     * @memberof RecoveryJobKeyPairStatus
     */
    state_code?: RecoveryJobKeyPairStatusStateCodeEnum;
    /**
     * 복구 결과
     * @type {string}
     * @memberof RecoveryJobKeyPairStatus
     */
    result_code?: RecoveryJobKeyPairStatusResultCodeEnum;
    /**
     * 복구, 롤백 상태
     * @type {string}
     * @memberof RecoveryJobKeyPairStatus
     */
    type_code?: RecoveryJobKeyPairStatusTypeCodeEnum;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryJobKeyPairStatus
     */
    failed_reason?: Message;
    /**
     * 롤백 여부
     * @type {boolean}
     * @memberof RecoveryJobKeyPairStatus
     */
    rollback_flag?: boolean;
}


/**
 * @export
 */
export const RecoveryJobKeyPairStatusRecoveryPointTypeCodeEnum = {
    latest: 'dr.recovery.recovery_point.type.latest',
    latest_snapshot: 'dr.recovery.recovery_point.type.latest_snapshot',
    snapshot: 'dr.recovery.recovery_point.type.snapshot'
} as const;
export type RecoveryJobKeyPairStatusRecoveryPointTypeCodeEnum = typeof RecoveryJobKeyPairStatusRecoveryPointTypeCodeEnum[keyof typeof RecoveryJobKeyPairStatusRecoveryPointTypeCodeEnum];

/**
 * @export
 */
export const RecoveryJobKeyPairStatusStateCodeEnum = {
    waiting: 'waiting',
    running: 'running',
    done: 'done'
} as const;
export type RecoveryJobKeyPairStatusStateCodeEnum = typeof RecoveryJobKeyPairStatusStateCodeEnum[keyof typeof RecoveryJobKeyPairStatusStateCodeEnum];

/**
 * @export
 */
export const RecoveryJobKeyPairStatusResultCodeEnum = {
    success: 'success',
    failed: 'failed',
    excepted: 'excepted',
    ignored: 'ignored',
    canceled: 'canceled'
} as const;
export type RecoveryJobKeyPairStatusResultCodeEnum = typeof RecoveryJobKeyPairStatusResultCodeEnum[keyof typeof RecoveryJobKeyPairStatusResultCodeEnum];

/**
 * @export
 */
export const RecoveryJobKeyPairStatusTypeCodeEnum = {
    create: 'dr.migration.task.create',
    delete: 'dr.migration.task.delete'
} as const;
export type RecoveryJobKeyPairStatusTypeCodeEnum = typeof RecoveryJobKeyPairStatusTypeCodeEnum[keyof typeof RecoveryJobKeyPairStatusTypeCodeEnum];


/**
 * Check if a given object implements the RecoveryJobKeyPairStatus interface.
 */
export function instanceOfRecoveryJobKeyPairStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryJobKeyPairStatusFromJSON(json: any): RecoveryJobKeyPairStatus {
    return RecoveryJobKeyPairStatusFromJSONTyped(json, false);
}

export function RecoveryJobKeyPairStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryJobKeyPairStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keypair': !exists(json, 'keypair') ? undefined : ClusterKeyPairFromJSON(json['keypair']),
        'recovery_point_type_code': !exists(json, 'recovery_point_type_code') ? undefined : json['recovery_point_type_code'],
        'recovery_point': !exists(json, 'recovery_point') ? undefined : json['recovery_point'],
        'started_at': !exists(json, 'started_at') ? undefined : json['started_at'],
        'finished_at': !exists(json, 'finished_at') ? undefined : json['finished_at'],
        'state_code': !exists(json, 'state_code') ? undefined : json['state_code'],
        'result_code': !exists(json, 'result_code') ? undefined : json['result_code'],
        'type_code': !exists(json, 'type_code') ? undefined : json['type_code'],
        'failed_reason': !exists(json, 'failed_reason') ? undefined : MessageFromJSON(json['failed_reason']),
        'rollback_flag': !exists(json, 'rollback_flag') ? undefined : json['rollback_flag'],
    };
}

export function RecoveryJobKeyPairStatusToJSON(value?: RecoveryJobKeyPairStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keypair': ClusterKeyPairToJSON(value.keypair),
        'recovery_point_type_code': value.recovery_point_type_code,
        'recovery_point': value.recovery_point,
        'started_at': value.started_at,
        'finished_at': value.finished_at,
        'state_code': value.state_code,
        'result_code': value.result_code,
        'type_code': value.type_code,
        'failed_reason': MessageToJSON(value.failed_reason),
        'rollback_flag': value.rollback_flag,
    };
}

