/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';
import type { RecoveryPlan } from './RecoveryPlan';
import {
    RecoveryPlanFromJSON,
    RecoveryPlanFromJSONTyped,
    RecoveryPlanToJSON,
} from './RecoveryPlan';

/**
 * 
 * @export
 * @interface RecoveryGroupsGroupIdPlansGet200Response
 */
export interface RecoveryGroupsGroupIdPlansGet200Response {
    /**
     * 
     * @type {Array<RecoveryPlan>}
     * @memberof RecoveryGroupsGroupIdPlansGet200Response
     */
    plans?: Array<RecoveryPlan>;
    /**
     * 
     * @type {Pagination}
     * @memberof RecoveryGroupsGroupIdPlansGet200Response
     */
    pagination?: Pagination;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryGroupsGroupIdPlansGet200Response
     */
    message?: Message;
}

/**
 * Check if a given object implements the RecoveryGroupsGroupIdPlansGet200Response interface.
 */
export function instanceOfRecoveryGroupsGroupIdPlansGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryGroupsGroupIdPlansGet200ResponseFromJSON(json: any): RecoveryGroupsGroupIdPlansGet200Response {
    return RecoveryGroupsGroupIdPlansGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryGroupsGroupIdPlansGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryGroupsGroupIdPlansGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plans': !exists(json, 'plans') ? undefined : ((json['plans'] as Array<any>).map(RecoveryPlanFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationFromJSON(json['pagination']),
        'message': !exists(json, 'message') ? undefined : MessageFromJSON(json['message']),
    };
}

export function RecoveryGroupsGroupIdPlansGet200ResponseToJSON(value?: RecoveryGroupsGroupIdPlansGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plans': value.plans === undefined ? undefined : ((value.plans as Array<any>).map(RecoveryPlanToJSON)),
        'pagination': PaginationToJSON(value.pagination),
        'message': MessageToJSON(value.message),
    };
}

