/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterRouter } from './ClusterRouter';
import {
    ClusterRouterFromJSON,
    ClusterRouterFromJSONTyped,
    ClusterRouterToJSON,
} from './ClusterRouter';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 라우터 복구 상태
 * @export
 * @interface RecoveryJobRouterStatus
 */
export interface RecoveryJobRouterStatus {
    /**
     * 
     * @type {ClusterRouter}
     * @memberof RecoveryJobRouterStatus
     */
    router?: ClusterRouter;
    /**
     * 데이터 시점 유형
     * @type {string}
     * @memberof RecoveryJobRouterStatus
     */
    recovery_point_type_code?: RecoveryJobRouterStatusRecoveryPointTypeCodeEnum;
    /**
     * 복구 데이터 시점
     * @type {number}
     * @memberof RecoveryJobRouterStatus
     */
    recovery_point?: number;
    /**
     * 복구 시작 일시
     * @type {number}
     * @memberof RecoveryJobRouterStatus
     */
    started_at?: number;
    /**
     * 복구 종료 일시
     * @type {number}
     * @memberof RecoveryJobRouterStatus
     */
    finished_at?: number;
    /**
     * 복구 상태
     * @type {string}
     * @memberof RecoveryJobRouterStatus
     */
    state_code?: RecoveryJobRouterStatusStateCodeEnum;
    /**
     * 복구 결과
     * @type {string}
     * @memberof RecoveryJobRouterStatus
     */
    result_code?: RecoveryJobRouterStatusResultCodeEnum;
    /**
     * 복구, 롤백 상태
     * @type {string}
     * @memberof RecoveryJobRouterStatus
     */
    type_code?: RecoveryJobRouterStatusTypeCodeEnum;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryJobRouterStatus
     */
    failed_reason?: Message;
    /**
     * 롤백 여부
     * @type {boolean}
     * @memberof RecoveryJobRouterStatus
     */
    rollback_flag?: boolean;
}


/**
 * @export
 */
export const RecoveryJobRouterStatusRecoveryPointTypeCodeEnum = {
    latest: 'dr.recovery.recovery_point.type.latest',
    latest_snapshot: 'dr.recovery.recovery_point.type.latest_snapshot',
    snapshot: 'dr.recovery.recovery_point.type.snapshot'
} as const;
export type RecoveryJobRouterStatusRecoveryPointTypeCodeEnum = typeof RecoveryJobRouterStatusRecoveryPointTypeCodeEnum[keyof typeof RecoveryJobRouterStatusRecoveryPointTypeCodeEnum];

/**
 * @export
 */
export const RecoveryJobRouterStatusStateCodeEnum = {
    waiting: 'waiting',
    running: 'running',
    done: 'done'
} as const;
export type RecoveryJobRouterStatusStateCodeEnum = typeof RecoveryJobRouterStatusStateCodeEnum[keyof typeof RecoveryJobRouterStatusStateCodeEnum];

/**
 * @export
 */
export const RecoveryJobRouterStatusResultCodeEnum = {
    success: 'success',
    failed: 'failed',
    excepted: 'excepted',
    ignored: 'ignored',
    canceled: 'canceled'
} as const;
export type RecoveryJobRouterStatusResultCodeEnum = typeof RecoveryJobRouterStatusResultCodeEnum[keyof typeof RecoveryJobRouterStatusResultCodeEnum];

/**
 * @export
 */
export const RecoveryJobRouterStatusTypeCodeEnum = {
    create: 'dr.migration.task.create',
    delete: 'dr.migration.task.delete'
} as const;
export type RecoveryJobRouterStatusTypeCodeEnum = typeof RecoveryJobRouterStatusTypeCodeEnum[keyof typeof RecoveryJobRouterStatusTypeCodeEnum];


/**
 * Check if a given object implements the RecoveryJobRouterStatus interface.
 */
export function instanceOfRecoveryJobRouterStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryJobRouterStatusFromJSON(json: any): RecoveryJobRouterStatus {
    return RecoveryJobRouterStatusFromJSONTyped(json, false);
}

export function RecoveryJobRouterStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryJobRouterStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'router': !exists(json, 'router') ? undefined : ClusterRouterFromJSON(json['router']),
        'recovery_point_type_code': !exists(json, 'recovery_point_type_code') ? undefined : json['recovery_point_type_code'],
        'recovery_point': !exists(json, 'recovery_point') ? undefined : json['recovery_point'],
        'started_at': !exists(json, 'started_at') ? undefined : json['started_at'],
        'finished_at': !exists(json, 'finished_at') ? undefined : json['finished_at'],
        'state_code': !exists(json, 'state_code') ? undefined : json['state_code'],
        'result_code': !exists(json, 'result_code') ? undefined : json['result_code'],
        'type_code': !exists(json, 'type_code') ? undefined : json['type_code'],
        'failed_reason': !exists(json, 'failed_reason') ? undefined : MessageFromJSON(json['failed_reason']),
        'rollback_flag': !exists(json, 'rollback_flag') ? undefined : json['rollback_flag'],
    };
}

export function RecoveryJobRouterStatusToJSON(value?: RecoveryJobRouterStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'router': ClusterRouterToJSON(value.router),
        'recovery_point_type_code': value.recovery_point_type_code,
        'recovery_point': value.recovery_point,
        'started_at': value.started_at,
        'finished_at': value.finished_at,
        'state_code': value.state_code,
        'result_code': value.result_code,
        'type_code': value.type_code,
        'failed_reason': MessageToJSON(value.failed_reason),
        'rollback_flag': value.rollback_flag,
    };
}

