/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecoveryDashboardSummaryVolumesGet200ResponseSummary
 */
export interface RecoveryDashboardSummaryVolumesGet200ResponseSummary {
    /**
     * 보호 볼륨 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryVolumesGet200ResponseSummary
     */
    protection_volume?: number;
}

/**
 * Check if a given object implements the RecoveryDashboardSummaryVolumesGet200ResponseSummary interface.
 */
export function instanceOfRecoveryDashboardSummaryVolumesGet200ResponseSummary(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardSummaryVolumesGet200ResponseSummaryFromJSON(json: any): RecoveryDashboardSummaryVolumesGet200ResponseSummary {
    return RecoveryDashboardSummaryVolumesGet200ResponseSummaryFromJSONTyped(json, false);
}

export function RecoveryDashboardSummaryVolumesGet200ResponseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardSummaryVolumesGet200ResponseSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'protection_volume': !exists(json, 'protection_volume') ? undefined : json['protection_volume'],
    };
}

export function RecoveryDashboardSummaryVolumesGet200ResponseSummaryToJSON(value?: RecoveryDashboardSummaryVolumesGet200ResponseSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'protection_volume': value.protection_volume,
    };
}

