/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RecoveryTaskLog } from './RecoveryTaskLog';
import {
    RecoveryTaskLogFromJSON,
    RecoveryTaskLogFromJSONTyped,
    RecoveryTaskLogToJSON,
} from './RecoveryTaskLog';

/**
 * 
 * @export
 * @interface RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response
 */
export interface RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response {
    /**
     * 
     * @type {Array<RecoveryTaskLog>}
     * @memberof RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response
     */
    task_logs?: Array<RecoveryTaskLog>;
}

/**
 * Check if a given object implements the RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response interface.
 */
export function instanceOfRecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200ResponseFromJSON(json: any): RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response {
    return RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'task_logs': !exists(json, 'task_logs') ? undefined : ((json['task_logs'] as Array<any>).map(RecoveryTaskLogFromJSON)),
    };
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200ResponseToJSON(value?: RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_logs': value.task_logs === undefined ? undefined : ((value.task_logs as Array<any>).map(RecoveryTaskLogToJSON)),
    };
}

