/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecoveryDashboardSummaryInstancesGet200ResponseSummary
 */
export interface RecoveryDashboardSummaryInstancesGet200ResponseSummary {
    /**
     * 모든 인스턴스 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryInstancesGet200ResponseSummary
     */
    total_instance?: number;
    /**
     * 보호 인스턴스 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryInstancesGet200ResponseSummary
     */
    protection_instance?: number;
}

/**
 * Check if a given object implements the RecoveryDashboardSummaryInstancesGet200ResponseSummary interface.
 */
export function instanceOfRecoveryDashboardSummaryInstancesGet200ResponseSummary(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardSummaryInstancesGet200ResponseSummaryFromJSON(json: any): RecoveryDashboardSummaryInstancesGet200ResponseSummary {
    return RecoveryDashboardSummaryInstancesGet200ResponseSummaryFromJSONTyped(json, false);
}

export function RecoveryDashboardSummaryInstancesGet200ResponseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardSummaryInstancesGet200ResponseSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total_instance': !exists(json, 'total_instance') ? undefined : json['total_instance'],
        'protection_instance': !exists(json, 'protection_instance') ? undefined : json['protection_instance'],
    };
}

export function RecoveryDashboardSummaryInstancesGet200ResponseSummaryToJSON(value?: RecoveryDashboardSummaryInstancesGet200ResponseSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_instance': value.total_instance,
        'protection_instance': value.protection_instance,
    };
}

