/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RecoveryJobVolumeStatus } from './RecoveryJobVolumeStatus';
import {
    RecoveryJobVolumeStatusFromJSON,
    RecoveryJobVolumeStatusFromJSONTyped,
    RecoveryJobVolumeStatusToJSON,
} from './RecoveryJobVolumeStatus';

/**
 * 
 * @export
 * @interface RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response
 */
export interface RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response {
    /**
     * 
     * @type {Array<RecoveryJobVolumeStatus>}
     * @memberof RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response
     */
    volumes?: Array<RecoveryJobVolumeStatus>;
}

/**
 * Check if a given object implements the RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response interface.
 */
export function instanceOfRecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200ResponseFromJSON(json: any): RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response {
    return RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'volumes': !exists(json, 'volumes') ? undefined : ((json['volumes'] as Array<any>).map(RecoveryJobVolumeStatusFromJSON)),
    };
}

export function RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200ResponseToJSON(value?: RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'volumes': value.volumes === undefined ? undefined : ((value.volumes as Array<any>).map(RecoveryJobVolumeStatusToJSON)),
    };
}

