/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecoveryDashboardSummaryGroupsGet200ResponseSummary
 */
export interface RecoveryDashboardSummaryGroupsGet200ResponseSummary {
    /**
     * 모든 보호 그룹 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryGroupsGet200ResponseSummary
     */
    total_group?: number;
    /**
     * normal 보호 그룹 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryGroupsGet200ResponseSummary
     */
    normal_group?: number;
    /**
     * warning 보호 그룹 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryGroupsGet200ResponseSummary
     */
    warning_group?: number;
    /**
     * critical 보호 그룹 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryGroupsGet200ResponseSummary
     */
    critical_group?: number;
    /**
     * emergency 보호 그룹 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryGroupsGet200ResponseSummary
     */
    emergency_group?: number;
}

/**
 * Check if a given object implements the RecoveryDashboardSummaryGroupsGet200ResponseSummary interface.
 */
export function instanceOfRecoveryDashboardSummaryGroupsGet200ResponseSummary(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardSummaryGroupsGet200ResponseSummaryFromJSON(json: any): RecoveryDashboardSummaryGroupsGet200ResponseSummary {
    return RecoveryDashboardSummaryGroupsGet200ResponseSummaryFromJSONTyped(json, false);
}

export function RecoveryDashboardSummaryGroupsGet200ResponseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardSummaryGroupsGet200ResponseSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total_group': !exists(json, 'total_group') ? undefined : json['total_group'],
        'normal_group': !exists(json, 'normal_group') ? undefined : json['normal_group'],
        'warning_group': !exists(json, 'warning_group') ? undefined : json['warning_group'],
        'critical_group': !exists(json, 'critical_group') ? undefined : json['critical_group'],
        'emergency_group': !exists(json, 'emergency_group') ? undefined : json['emergency_group'],
    };
}

export function RecoveryDashboardSummaryGroupsGet200ResponseSummaryToJSON(value?: RecoveryDashboardSummaryGroupsGet200ResponseSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_group': value.total_group,
        'normal_group': value.normal_group,
        'warning_group': value.warning_group,
        'critical_group': value.critical_group,
        'emergency_group': value.emergency_group,
    };
}

