/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { RecoveryDashboardSummaryJobsGet200ResponseSummaryInner } from './RecoveryDashboardSummaryJobsGet200ResponseSummaryInner';
import {
    RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerFromJSON,
    RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerFromJSONTyped,
    RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerToJSON,
} from './RecoveryDashboardSummaryJobsGet200ResponseSummaryInner';

/**
 * 
 * @export
 * @interface RecoveryDashboardSummaryJobsGet200Response
 */
export interface RecoveryDashboardSummaryJobsGet200Response {
    /**
     * 
     * @type {Array<RecoveryDashboardSummaryJobsGet200ResponseSummaryInner>}
     * @memberof RecoveryDashboardSummaryJobsGet200Response
     */
    summary?: Array<RecoveryDashboardSummaryJobsGet200ResponseSummaryInner>;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryDashboardSummaryJobsGet200Response
     */
    message?: Message;
}

/**
 * Check if a given object implements the RecoveryDashboardSummaryJobsGet200Response interface.
 */
export function instanceOfRecoveryDashboardSummaryJobsGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardSummaryJobsGet200ResponseFromJSON(json: any): RecoveryDashboardSummaryJobsGet200Response {
    return RecoveryDashboardSummaryJobsGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryDashboardSummaryJobsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardSummaryJobsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'summary': !exists(json, 'summary') ? undefined : ((json['summary'] as Array<any>).map(RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerFromJSON)),
        'message': !exists(json, 'message') ? undefined : MessageFromJSON(json['message']),
    };
}

export function RecoveryDashboardSummaryJobsGet200ResponseToJSON(value?: RecoveryDashboardSummaryJobsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'summary': value.summary === undefined ? undefined : ((value.summary as Array<any>).map(RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerToJSON)),
        'message': MessageToJSON(value.message),
    };
}

