/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 재해복구작업 상태
 * @export
 * @interface RecoveryJobStatus
 */
export interface RecoveryJobStatus {
    /**
     * 작업 시작일시
     * @type {number}
     * @memberof RecoveryJobStatus
     */
    started_at?: number;
    /**
     * 작업 종료일시
     * @type {number}
     * @memberof RecoveryJobStatus
     */
    finished_at?: number;
    /**
     * 작업 소요시간
     * @type {number}
     * @memberof RecoveryJobStatus
     */
    elapsed_time?: number;
    /**
     * Operation
     * @type {string}
     * @memberof RecoveryJobStatus
     */
    operation_code?: RecoveryJobStatusOperationCodeEnum;
    /**
     * 작업 상태
     * @type {string}
     * @memberof RecoveryJobStatus
     */
    state_code?: RecoveryJobStatusStateCodeEnum;
    /**
     * 실행 결과
     * @type {string}
     * @memberof RecoveryJobStatus
     */
    result_code?: RecoveryJobStatusResultCodeEnum;
    /**
     * 경고 여부
     * @type {boolean}
     * @memberof RecoveryJobStatus
     */
    warning_flag?: boolean;
    /**
     * 경고 사유 목록
     * @type {Array<Message>}
     * @memberof RecoveryJobStatus
     */
    warning_reasons?: Array<Message>;
    /**
     * 실패 사유 목록
     * @type {Array<Message>}
     * @memberof RecoveryJobStatus
     */
    failed_reasons?: Array<Message>;
    /**
     * 재개예정일시
     * @type {number}
     * @memberof RecoveryJobStatus
     */
    resume_at?: number;
    /**
     * 롤백예정일시
     * @type {number}
     * @memberof RecoveryJobStatus
     */
    rollback_at?: number;
}


/**
 * @export
 */
export const RecoveryJobStatusOperationCodeEnum = {
    run: 'run',
    pause: 'pause',
    cancel: 'cancel',
    retry: 'retry',
    rollback: 'rollback',
    retry_rollback: 'retry-rollback',
    ignore_rollback: 'ignore-rollback',
    confirm: 'confirm',
    retry_confirm: 'retry-confirm',
    cancel_confirm: 'cancel-confirm'
} as const;
export type RecoveryJobStatusOperationCodeEnum = typeof RecoveryJobStatusOperationCodeEnum[keyof typeof RecoveryJobStatusOperationCodeEnum];

/**
 * @export
 */
export const RecoveryJobStatusStateCodeEnum = {
    waiting: 'dr.recovery.job.state.waiting',
    pending: 'dr.recovery.job.state.pending',
    running: 'dr.recovery.job.state.running',
    canceling: 'dr.recovery.job.state.canceling',
    paused: 'dr.recovery.job.state.paused',
    completed: 'dr.recovery.job.state.completed',
    clearing: 'dr.recovery.job.state.clearing',
    clear_failed: 'dr.recovery.job.state.clear-failed',
    reporting: 'dr.recovery.job.state.reporting',
    finished: 'dr.recovery.job.state.finished'
} as const;
export type RecoveryJobStatusStateCodeEnum = typeof RecoveryJobStatusStateCodeEnum[keyof typeof RecoveryJobStatusStateCodeEnum];

/**
 * @export
 */
export const RecoveryJobStatusResultCodeEnum = {
    success: 'dr.recovery.result.success',
    partial_success: 'dr.recovery.result.partial_success',
    failed: 'dr.recovery.result.failed',
    canceled: 'dr.recovery.result.canceled'
} as const;
export type RecoveryJobStatusResultCodeEnum = typeof RecoveryJobStatusResultCodeEnum[keyof typeof RecoveryJobStatusResultCodeEnum];


/**
 * Check if a given object implements the RecoveryJobStatus interface.
 */
export function instanceOfRecoveryJobStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryJobStatusFromJSON(json: any): RecoveryJobStatus {
    return RecoveryJobStatusFromJSONTyped(json, false);
}

export function RecoveryJobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryJobStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'started_at': !exists(json, 'started_at') ? undefined : json['started_at'],
        'finished_at': !exists(json, 'finished_at') ? undefined : json['finished_at'],
        'elapsed_time': !exists(json, 'elapsed_time') ? undefined : json['elapsed_time'],
        'operation_code': !exists(json, 'operation_code') ? undefined : json['operation_code'],
        'state_code': !exists(json, 'state_code') ? undefined : json['state_code'],
        'result_code': !exists(json, 'result_code') ? undefined : json['result_code'],
        'warning_flag': !exists(json, 'warning_flag') ? undefined : json['warning_flag'],
        'warning_reasons': !exists(json, 'warning_reasons') ? undefined : ((json['warning_reasons'] as Array<any>).map(MessageFromJSON)),
        'failed_reasons': !exists(json, 'failed_reasons') ? undefined : ((json['failed_reasons'] as Array<any>).map(MessageFromJSON)),
        'resume_at': !exists(json, 'resume_at') ? undefined : json['resume_at'],
        'rollback_at': !exists(json, 'rollback_at') ? undefined : json['rollback_at'],
    };
}

export function RecoveryJobStatusToJSON(value?: RecoveryJobStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'started_at': value.started_at,
        'finished_at': value.finished_at,
        'elapsed_time': value.elapsed_time,
        'operation_code': value.operation_code,
        'state_code': value.state_code,
        'result_code': value.result_code,
        'warning_flag': value.warning_flag,
        'warning_reasons': value.warning_reasons === undefined ? undefined : ((value.warning_reasons as Array<any>).map(MessageToJSON)),
        'failed_reasons': value.failed_reasons === undefined ? undefined : ((value.failed_reasons as Array<any>).map(MessageToJSON)),
        'resume_at': value.resume_at,
        'rollback_at': value.rollback_at,
    };
}

