/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterRelationship } from './ClusterRelationship';
import {
    ClusterRelationshipFromJSON,
    ClusterRelationshipFromJSONTyped,
    ClusterRelationshipToJSON,
} from './ClusterRelationship';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';

/**
 * 
 * @export
 * @interface RecoveryDashboardClusterRelationshipsGet200Response
 */
export interface RecoveryDashboardClusterRelationshipsGet200Response {
    /**
     * 
     * @type {Array<ClusterRelationship>}
     * @memberof RecoveryDashboardClusterRelationshipsGet200Response
     */
    cluster_relationships?: Array<ClusterRelationship>;
    /**
     * 
     * @type {Pagination}
     * @memberof RecoveryDashboardClusterRelationshipsGet200Response
     */
    pagination?: Pagination;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryDashboardClusterRelationshipsGet200Response
     */
    message?: Message;
}

/**
 * Check if a given object implements the RecoveryDashboardClusterRelationshipsGet200Response interface.
 */
export function instanceOfRecoveryDashboardClusterRelationshipsGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardClusterRelationshipsGet200ResponseFromJSON(json: any): RecoveryDashboardClusterRelationshipsGet200Response {
    return RecoveryDashboardClusterRelationshipsGet200ResponseFromJSONTyped(json, false);
}

export function RecoveryDashboardClusterRelationshipsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardClusterRelationshipsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cluster_relationships': !exists(json, 'cluster_relationships') ? undefined : ((json['cluster_relationships'] as Array<any>).map(ClusterRelationshipFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationFromJSON(json['pagination']),
        'message': !exists(json, 'message') ? undefined : MessageFromJSON(json['message']),
    };
}

export function RecoveryDashboardClusterRelationshipsGet200ResponseToJSON(value?: RecoveryDashboardClusterRelationshipsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cluster_relationships': value.cluster_relationships === undefined ? undefined : ((value.cluster_relationships as Array<any>).map(ClusterRelationshipToJSON)),
        'pagination': PaginationToJSON(value.pagination),
        'message': MessageToJSON(value.message),
    };
}

