/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { RecoveryPlan } from './RecoveryPlan';
import {
    RecoveryPlanFromJSON,
    RecoveryPlanFromJSONTyped,
    RecoveryPlanToJSON,
} from './RecoveryPlan';

/**
 * 
 * @export
 * @interface RecoveryGroupsGroupIdPlansPost201Response
 */
export interface RecoveryGroupsGroupIdPlansPost201Response {
    /**
     * 
     * @type {RecoveryPlan}
     * @memberof RecoveryGroupsGroupIdPlansPost201Response
     */
    plan?: RecoveryPlan;
    /**
     * 
     * @type {Message}
     * @memberof RecoveryGroupsGroupIdPlansPost201Response
     */
    message?: Message;
}

/**
 * Check if a given object implements the RecoveryGroupsGroupIdPlansPost201Response interface.
 */
export function instanceOfRecoveryGroupsGroupIdPlansPost201Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryGroupsGroupIdPlansPost201ResponseFromJSON(json: any): RecoveryGroupsGroupIdPlansPost201Response {
    return RecoveryGroupsGroupIdPlansPost201ResponseFromJSONTyped(json, false);
}

export function RecoveryGroupsGroupIdPlansPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryGroupsGroupIdPlansPost201Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plan': !exists(json, 'plan') ? undefined : RecoveryPlanFromJSON(json['plan']),
        'message': !exists(json, 'message') ? undefined : MessageFromJSON(json['message']),
    };
}

export function RecoveryGroupsGroupIdPlansPost201ResponseToJSON(value?: RecoveryGroupsGroupIdPlansPost201Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plan': RecoveryPlanToJSON(value.plan),
        'message': MessageToJSON(value.message),
    };
}

