/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceTemplate } from './InstanceTemplate';
import {
    InstanceTemplateFromJSON,
    InstanceTemplateFromJSONTyped,
    InstanceTemplateToJSON,
} from './InstanceTemplate';

/**
 * 
 * @export
 * @interface RecoveryTemplatesPostRequest
 */
export interface RecoveryTemplatesPostRequest {
    /**
     * 
     * @type {InstanceTemplate}
     * @memberof RecoveryTemplatesPostRequest
     */
    template?: InstanceTemplate;
}

/**
 * Check if a given object implements the RecoveryTemplatesPostRequest interface.
 */
export function instanceOfRecoveryTemplatesPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryTemplatesPostRequestFromJSON(json: any): RecoveryTemplatesPostRequest {
    return RecoveryTemplatesPostRequestFromJSONTyped(json, false);
}

export function RecoveryTemplatesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryTemplatesPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'template': !exists(json, 'template') ? undefined : InstanceTemplateFromJSON(json['template']),
    };
}

export function RecoveryTemplatesPostRequestToJSON(value?: RecoveryTemplatesPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'template': InstanceTemplateToJSON(value.template),
    };
}

