/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecoveryDashboardSummaryJobsGet200ResponseSummaryInner
 */
export interface RecoveryDashboardSummaryJobsGet200ResponseSummaryInner {
    /**
     * 일자(YYYYMMDD)
     * @type {string}
     * @memberof RecoveryDashboardSummaryJobsGet200ResponseSummaryInner
     */
    date?: string;
    /**
     * 성공 작업 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryJobsGet200ResponseSummaryInner
     */
    success?: number;
    /**
     * 실패 작업 수
     * @type {number}
     * @memberof RecoveryDashboardSummaryJobsGet200ResponseSummaryInner
     */
    fail?: number;
}

/**
 * Check if a given object implements the RecoveryDashboardSummaryJobsGet200ResponseSummaryInner interface.
 */
export function instanceOfRecoveryDashboardSummaryJobsGet200ResponseSummaryInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerFromJSON(json: any): RecoveryDashboardSummaryJobsGet200ResponseSummaryInner {
    return RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerFromJSONTyped(json, false);
}

export function RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryDashboardSummaryJobsGet200ResponseSummaryInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : json['date'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'fail': !exists(json, 'fail') ? undefined : json['fail'],
    };
}

export function RecoveryDashboardSummaryJobsGet200ResponseSummaryInnerToJSON(value?: RecoveryDashboardSummaryJobsGet200ResponseSummaryInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'success': value.success,
        'fail': value.fail,
    };
}

