/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 솔루션 역할
 * @export
 * @interface Role
 */
export interface Role {
    /**
     * 솔루션 역할의 ID
     * @type {number}
     * @memberof Role
     */
    id?: number;
    /**
     * 솔루션 이름
     * @type {string}
     * @memberof Role
     */
    solution?: string;
    /**
     * 역할
     * @type {string}
     * @memberof Role
     */
    role?: RoleRoleEnum;
}


/**
 * @export
 */
export const RoleRoleEnum = {
    manager: 'manager',
    operator: 'operator',
    viewer: 'viewer'
} as const;
export type RoleRoleEnum = typeof RoleRoleEnum[keyof typeof RoleRoleEnum];


/**
 * Check if a given object implements the Role interface.
 */
export function instanceOfRole(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RoleFromJSON(json: any): Role {
    return RoleFromJSONTyped(json, false);
}

export function RoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Role {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'solution': !exists(json, 'solution') ? undefined : json['solution'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function RoleToJSON(value?: Role | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'solution': value.solution,
        'role': value.role,
    };
}

