/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterRouter } from './ClusterRouter';
import {
    ClusterRouterFromJSON,
    ClusterRouterFromJSONTyped,
    ClusterRouterToJSON,
} from './ClusterRouter';

/**
 * 
 * @export
 * @interface RouterRecoveryResult
 */
export interface RouterRecoveryResult {
    /**
     * 
     * @type {ClusterRouter}
     * @memberof RouterRecoveryResult
     */
    protection_cluster_router?: ClusterRouter;
    /**
     * 
     * @type {ClusterRouter}
     * @memberof RouterRecoveryResult
     */
    recovery_cluster_router?: ClusterRouter;
}

/**
 * Check if a given object implements the RouterRecoveryResult interface.
 */
export function instanceOfRouterRecoveryResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouterRecoveryResultFromJSON(json: any): RouterRecoveryResult {
    return RouterRecoveryResultFromJSONTyped(json, false);
}

export function RouterRecoveryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouterRecoveryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'protection_cluster_router': !exists(json, 'protection_cluster_router') ? undefined : ClusterRouterFromJSON(json['protection_cluster_router']),
        'recovery_cluster_router': !exists(json, 'recovery_cluster_router') ? undefined : ClusterRouterFromJSON(json['recovery_cluster_router']),
    };
}

export function RouterRecoveryResultToJSON(value?: RouterRecoveryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'protection_cluster_router': ClusterRouterToJSON(value.protection_cluster_router),
        'recovery_cluster_router': ClusterRouterToJSON(value.recovery_cluster_router),
    };
}

