/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 테넌트
 * @export
 * @interface TenantSolution
 */
export interface TenantSolution {
    /**
     * 솔루션 이름
     * @type {string}
     * @memberof TenantSolution
     */
    name?: string;
}

/**
 * Check if a given object implements the TenantSolution interface.
 */
export function instanceOfTenantSolution(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TenantSolutionFromJSON(json: any): TenantSolution {
    return TenantSolutionFromJSONTyped(json, false);
}

export function TenantSolutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantSolution {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function TenantSolutionToJSON(value?: TenantSolution | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

