/* tslint:disable */
/* eslint-disable */
/**
 * CDM-DisasterRecovery
 * 설명추가
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RecoveryGroupsGroupIdDelete200Response,
  RecoveryGroupsGroupIdJobsGet200Response,
  RecoveryGroupsGroupIdJobsJobIdMonitorGet200Response,
  RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response,
  RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response,
  RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response,
  RecoveryGroupsGroupIdJobsJobIdMonitorsGet200Response,
  RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequest,
  RecoveryGroupsGroupIdJobsJobIdRetryPostRequest,
  RecoveryGroupsGroupIdJobsPost201Response,
  RecoveryGroupsGroupIdJobsPost412Response,
  RecoveryGroupsGroupIdJobsPostRequest,
} from '../models/index';
import {
    RecoveryGroupsGroupIdDelete200ResponseFromJSON,
    RecoveryGroupsGroupIdDelete200ResponseToJSON,
    RecoveryGroupsGroupIdJobsGet200ResponseFromJSON,
    RecoveryGroupsGroupIdJobsGet200ResponseToJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorGet200ResponseFromJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorGet200ResponseToJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200ResponseFromJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200ResponseToJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200ResponseFromJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200ResponseToJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200ResponseFromJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200ResponseToJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorsGet200ResponseFromJSON,
    RecoveryGroupsGroupIdJobsJobIdMonitorsGet200ResponseToJSON,
    RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequestFromJSON,
    RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequestToJSON,
    RecoveryGroupsGroupIdJobsJobIdRetryPostRequestFromJSON,
    RecoveryGroupsGroupIdJobsJobIdRetryPostRequestToJSON,
    RecoveryGroupsGroupIdJobsPost201ResponseFromJSON,
    RecoveryGroupsGroupIdJobsPost201ResponseToJSON,
    RecoveryGroupsGroupIdJobsPost412ResponseFromJSON,
    RecoveryGroupsGroupIdJobsPost412ResponseToJSON,
    RecoveryGroupsGroupIdJobsPostRequestFromJSON,
    RecoveryGroupsGroupIdJobsPostRequestToJSON,
} from '../models/index';

export interface RecoveryGroupsGroupIdJobsGetRequest {
    group_id: number;
    plan_id: number;
    limit?: number;
    offset?: number;
    name?: string;
    type?: RecoveryGroupsGroupIdJobsGetTypeEnum;
}

export interface RecoveryGroupsGroupIdJobsJobIdCancelPostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdConfirmCancelPostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdConfirmPostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdConfirmRetryPostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdDeleteRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdForceDeletePostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdGetRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdMonitorGetRequest {
    group_id: number;
    job_id: number;
    interval?: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGetRequest {
    group_id: number;
    job_id: number;
    interval?: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGetRequest {
    group_id: number;
    job_id: number;
    interval?: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGetRequest {
    group_id: number;
    job_id: number;
    interval?: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdMonitorsGetRequest {
    group_id: number;
    job_id: number;
    interval?: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdPatchRequest {
    group_id: number;
    job_id: number;
    recovery_groups_group_id_jobs_post_request?: RecoveryGroupsGroupIdJobsPostRequest;
}

export interface RecoveryGroupsGroupIdJobsJobIdPauseExtendPostOperationRequest {
    group_id: number;
    job_id: number;
    recovery_groups_group_id_jobs_job_id_pause_extend_post_request?: RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequest;
}

export interface RecoveryGroupsGroupIdJobsJobIdPausePostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdResumePostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdRetryPostOperationRequest {
    group_id: number;
    job_id: number;
    recovery_groups_group_id_jobs_job_id_retry_post_request?: RecoveryGroupsGroupIdJobsJobIdRetryPostRequest;
}

export interface RecoveryGroupsGroupIdJobsJobIdRollbackExtendPostRequest {
    group_id: number;
    job_id: number;
    recovery_groups_group_id_jobs_job_id_pause_extend_post_request?: RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequest;
}

export interface RecoveryGroupsGroupIdJobsJobIdRollbackIgnorePostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdRollbackMigrationPostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdRollbackRetryPostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsJobIdRollbackSimulationPostRequest {
    group_id: number;
    job_id: number;
}

export interface RecoveryGroupsGroupIdJobsPostOperationRequest {
    group_id: number;
    recovery_groups_group_id_jobs_post_request?: RecoveryGroupsGroupIdJobsPostRequest;
}

/**
 * RecoveryJobApi - interface
 * 
 * @export
 * @interface RecoveryJobApiInterface
 */
export interface RecoveryJobApiInterface {
    /**
     * 설명추가
     * @summary 재해복구작업 목록 조회
     * @param {number} group_id 보호그룹 ID
     * @param {number} plan_id 재해복구계획 ID
     * @param {number} [limit] 한 페이지에 표시할 항목 개수
     * @param {number} [offset] 페이지에 표시할 항목 인덱스
     * @param {string} [name] 재해복구계획 이름
     * @param {'dr.recovery.type.simulation' | 'dr.recovery.type.migration'} [type] 복구 유형
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsGetRaw(requestParameters: RecoveryGroupsGroupIdJobsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsGet200Response>>;

    /**
     * 설명추가
     * 재해복구작업 목록 조회
     */
    recoveryGroupsGroupIdJobsGet(requestParameters: RecoveryGroupsGroupIdJobsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsGet200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 취소
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdCancelPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 취소
     */
    recoveryGroupsGroupIdJobsJobIdCancelPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 확정 취소
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdConfirmCancelPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 확정 취소
     */
    recoveryGroupsGroupIdJobsJobIdConfirmCancelPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 확정
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdConfirmPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 확정
     */
    recoveryGroupsGroupIdJobsJobIdConfirmPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 확정 재시도
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdConfirmRetryPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 확정 재시도
     */
    recoveryGroupsGroupIdJobsJobIdConfirmRetryPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 삭제
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdDeleteRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 삭제
     */
    recoveryGroupsGroupIdJobsJobIdDelete(requestParameters: RecoveryGroupsGroupIdJobsJobIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 재해복구작업을 클러스터의 상태와 상관없이 강제로 삭제한다.
     * @summary 재해복구작업 강제 삭제
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdForceDeletePostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdForceDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 재해복구작업을 클러스터의 상태와 상관없이 강제로 삭제한다.
     * 재해복구작업 강제 삭제
     */
    recoveryGroupsGroupIdJobsJobIdForceDeletePost(requestParameters: RecoveryGroupsGroupIdJobsJobIdForceDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 조회
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsPost201Response>>;

    /**
     * 설명추가
     * 재해복구작업 조회
     */
    recoveryGroupsGroupIdJobsJobIdGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsPost201Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 모니터링 (WebSocket 프로토콜 지원)
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {number} [interval] WebSocket 프로토콜을 사용할 때의 데이터 수신 간격 (sec)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdMonitorGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorGet200Response>>;

    /**
     * 설명추가
     * 재해복구작업 모니터링 (WebSocket 프로토콜 지원)
     */
    recoveryGroupsGroupIdJobsJobIdMonitorGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorGet200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 인스턴스 모니터링 (WebSocket 프로토콜 지원)
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {number} [interval] WebSocket 프로토콜을 사용할 때의 데이터 수신 간격 (sec)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdMonitorInstancesGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response>>;

    /**
     * 설명추가
     * 재해복구작업 인스턴스 모니터링 (WebSocket 프로토콜 지원)
     */
    recoveryGroupsGroupIdJobsJobIdMonitorInstancesGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 작업내역 모니터링 (WebSocket 프로토콜 지원)
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {number} [interval] WebSocket 프로토콜을 사용할 때의 데이터 수신 간격 (sec)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response>>;

    /**
     * 설명추가
     * 재해복구작업 작업내역 모니터링 (WebSocket 프로토콜 지원)
     */
    recoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 볼륨 모니터링 (WebSocket 프로토콜 지원)
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {number} [interval] WebSocket 프로토콜을 사용할 때의 데이터 수신 간격 (sec)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdMonitorVolumesGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response>>;

    /**
     * 설명추가
     * 재해복구작업 볼륨 모니터링 (WebSocket 프로토콜 지원)
     */
    recoveryGroupsGroupIdJobsJobIdMonitorVolumesGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 모든 상태 모니터링 (WebSocket 프로토콜 지원)
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {number} [interval] WebSocket 프로토콜을 사용할 때의 데이터 수신 간격 (sec)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdMonitorsGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorsGet200Response>>;

    /**
     * 설명추가
     * 재해복구작업 모든 상태 모니터링 (WebSocket 프로토콜 지원)
     */
    recoveryGroupsGroupIdJobsJobIdMonitorsGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorsGet200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 수정
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {RecoveryGroupsGroupIdJobsPostRequest} [recovery_groups_group_id_jobs_post_request] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdPatchRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsPost201Response>>;

    /**
     * 설명추가
     * 재해복구작업 수정
     */
    recoveryGroupsGroupIdJobsJobIdPatch(requestParameters: RecoveryGroupsGroupIdJobsJobIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsPost201Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 일시중지 시간 연장
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequest} [recovery_groups_group_id_jobs_job_id_pause_extend_post_request] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdPauseExtendPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdPauseExtendPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 일시중지 시간 연장
     */
    recoveryGroupsGroupIdJobsJobIdPauseExtendPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdPauseExtendPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 일시중지
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdPausePostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 일시중지
     */
    recoveryGroupsGroupIdJobsJobIdPausePost(requestParameters: RecoveryGroupsGroupIdJobsJobIdPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 재개
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdResumePostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 재개
     */
    recoveryGroupsGroupIdJobsJobIdResumePost(requestParameters: RecoveryGroupsGroupIdJobsJobIdResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 재시도 (재해복구)
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {RecoveryGroupsGroupIdJobsJobIdRetryPostRequest} [recovery_groups_group_id_jobs_job_id_retry_post_request] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdRetryPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRetryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 재시도 (재해복구)
     */
    recoveryGroupsGroupIdJobsJobIdRetryPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRetryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 롤백 대기시간 연장
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequest} [recovery_groups_group_id_jobs_job_id_pause_extend_post_request] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdRollbackExtendPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackExtendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 롤백 대기시간 연장
     */
    recoveryGroupsGroupIdJobsJobIdRollbackExtendPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackExtendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 롤백 무시
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdRollbackIgnorePostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackIgnorePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * 설명추가
     * 재해복구작업 롤백 무시
     */
    recoveryGroupsGroupIdJobsJobIdRollbackIgnorePost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackIgnorePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 설명추가
     * @summary 재해복구작업 롤백 (재해복구)
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdRollbackMigrationPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackMigrationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 롤백 (재해복구)
     */
    recoveryGroupsGroupIdJobsJobIdRollbackMigrationPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackMigrationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 롤백 재시도
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdRollbackRetryPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 롤백 재시도
     */
    recoveryGroupsGroupIdJobsJobIdRollbackRetryPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 롤백 (모의훈련)
     * @param {number} group_id 보호그룹 ID
     * @param {number} job_id 재해복구작업 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsJobIdRollbackSimulationPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackSimulationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>>;

    /**
     * 설명추가
     * 재해복구작업 롤백 (모의훈련)
     */
    recoveryGroupsGroupIdJobsJobIdRollbackSimulationPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackSimulationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response>;

    /**
     * 설명추가
     * @summary 재해복구작업 생성
     * @param {number} group_id 보호그룹 ID
     * @param {RecoveryGroupsGroupIdJobsPostRequest} [recovery_groups_group_id_jobs_post_request] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecoveryJobApiInterface
     */
    recoveryGroupsGroupIdJobsPostRaw(requestParameters: RecoveryGroupsGroupIdJobsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsPost201Response>>;

    /**
     * 설명추가
     * 재해복구작업 생성
     */
    recoveryGroupsGroupIdJobsPost(requestParameters: RecoveryGroupsGroupIdJobsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsPost201Response>;

}

/**
 * 
 */
export class RecoveryJobApi extends runtime.BaseAPI implements RecoveryJobApiInterface {

    /**
     * 설명추가
     * 재해복구작업 목록 조회
     */
    async recoveryGroupsGroupIdJobsGetRaw(requestParameters: RecoveryGroupsGroupIdJobsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsGet200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsGet.');
        }

        if (requestParameters.plan_id === null || requestParameters.plan_id === undefined) {
            throw new runtime.RequiredError('plan_id','Required parameter requestParameters.plan_id was null or undefined when calling recoveryGroupsGroupIdJobsGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"plan_id"}}`, encodeURIComponent(String(requestParameters.plan_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 목록 조회
     */
    async recoveryGroupsGroupIdJobsGet(requestParameters: RecoveryGroupsGroupIdJobsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsGet200Response> {
        const response = await this.recoveryGroupsGroupIdJobsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 취소
     */
    async recoveryGroupsGroupIdJobsJobIdCancelPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdCancelPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdCancelPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/cancel`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 취소
     */
    async recoveryGroupsGroupIdJobsJobIdCancelPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 확정 취소
     */
    async recoveryGroupsGroupIdJobsJobIdConfirmCancelPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdConfirmCancelPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdConfirmCancelPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/confirm/cancel`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 확정 취소
     */
    async recoveryGroupsGroupIdJobsJobIdConfirmCancelPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdConfirmCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 확정
     */
    async recoveryGroupsGroupIdJobsJobIdConfirmPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdConfirmPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdConfirmPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/confirm`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 확정
     */
    async recoveryGroupsGroupIdJobsJobIdConfirmPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdConfirmPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 확정 재시도
     */
    async recoveryGroupsGroupIdJobsJobIdConfirmRetryPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdConfirmRetryPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdConfirmRetryPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/confirm/retry`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 확정 재시도
     */
    async recoveryGroupsGroupIdJobsJobIdConfirmRetryPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdConfirmRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdConfirmRetryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 삭제
     */
    async recoveryGroupsGroupIdJobsJobIdDeleteRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdDelete.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 삭제
     */
    async recoveryGroupsGroupIdJobsJobIdDelete(requestParameters: RecoveryGroupsGroupIdJobsJobIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 재해복구작업을 클러스터의 상태와 상관없이 강제로 삭제한다.
     * 재해복구작업 강제 삭제
     */
    async recoveryGroupsGroupIdJobsJobIdForceDeletePostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdForceDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdForceDeletePost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdForceDeletePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/force-delete`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 재해복구작업을 클러스터의 상태와 상관없이 강제로 삭제한다.
     * 재해복구작업 강제 삭제
     */
    async recoveryGroupsGroupIdJobsJobIdForceDeletePost(requestParameters: RecoveryGroupsGroupIdJobsJobIdForceDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdForceDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 조회
     */
    async recoveryGroupsGroupIdJobsJobIdGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsPost201Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdGet.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsPost201ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 조회
     */
    async recoveryGroupsGroupIdJobsJobIdGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsPost201Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorGet200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorGet.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.interval !== undefined) {
            queryParameters['interval'] = requestParameters.interval;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/monitor`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsJobIdMonitorGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorGet200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdMonitorGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 인스턴스 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorInstancesGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorInstancesGet.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorInstancesGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.interval !== undefined) {
            queryParameters['interval'] = requestParameters.interval;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/monitor/instances`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 인스턴스 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorInstancesGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorInstancesGet200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdMonitorInstancesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 작업내역 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.interval !== undefined) {
            queryParameters['interval'] = requestParameters.interval;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/monitor/task-logs`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 작업내역 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGet200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdMonitorTaskLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 볼륨 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorVolumesGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorVolumesGet.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorVolumesGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.interval !== undefined) {
            queryParameters['interval'] = requestParameters.interval;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/monitor/volumes`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 볼륨 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorVolumesGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorVolumesGet200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdMonitorVolumesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 모든 상태 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorsGetRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsJobIdMonitorsGet200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorsGet.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdMonitorsGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.interval !== undefined) {
            queryParameters['interval'] = requestParameters.interval;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/monitors`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsJobIdMonitorsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 모든 상태 모니터링 (WebSocket 프로토콜 지원)
     */
    async recoveryGroupsGroupIdJobsJobIdMonitorsGet(requestParameters: RecoveryGroupsGroupIdJobsJobIdMonitorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsJobIdMonitorsGet200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdMonitorsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 수정
     */
    async recoveryGroupsGroupIdJobsJobIdPatchRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsPost201Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdPatch.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RecoveryGroupsGroupIdJobsPostRequestToJSON(requestParameters.recovery_groups_group_id_jobs_post_request),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsPost201ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 수정
     */
    async recoveryGroupsGroupIdJobsJobIdPatch(requestParameters: RecoveryGroupsGroupIdJobsJobIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsPost201Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 일시중지 시간 연장
     */
    async recoveryGroupsGroupIdJobsJobIdPauseExtendPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdPauseExtendPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdPauseExtendPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdPauseExtendPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/pause/extend`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequestToJSON(requestParameters.recovery_groups_group_id_jobs_job_id_pause_extend_post_request),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 일시중지 시간 연장
     */
    async recoveryGroupsGroupIdJobsJobIdPauseExtendPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdPauseExtendPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdPauseExtendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 일시중지
     */
    async recoveryGroupsGroupIdJobsJobIdPausePostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdPausePost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdPausePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/pause`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 일시중지
     */
    async recoveryGroupsGroupIdJobsJobIdPausePost(requestParameters: RecoveryGroupsGroupIdJobsJobIdPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdPausePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 재개
     */
    async recoveryGroupsGroupIdJobsJobIdResumePostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdResumePost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdResumePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/resume`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 재개
     */
    async recoveryGroupsGroupIdJobsJobIdResumePost(requestParameters: RecoveryGroupsGroupIdJobsJobIdResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdResumePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 재시도 (재해복구)
     */
    async recoveryGroupsGroupIdJobsJobIdRetryPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRetryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRetryPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRetryPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/retry`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecoveryGroupsGroupIdJobsJobIdRetryPostRequestToJSON(requestParameters.recovery_groups_group_id_jobs_job_id_retry_post_request),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 재시도 (재해복구)
     */
    async recoveryGroupsGroupIdJobsJobIdRetryPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRetryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdRetryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 대기시간 연장
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackExtendPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackExtendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackExtendPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackExtendPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/rollback/extend`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecoveryGroupsGroupIdJobsJobIdPauseExtendPostRequestToJSON(requestParameters.recovery_groups_group_id_jobs_job_id_pause_extend_post_request),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 대기시간 연장
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackExtendPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackExtendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdRollbackExtendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 무시
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackIgnorePostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackIgnorePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackIgnorePost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackIgnorePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/rollback/ignore`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 무시
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackIgnorePost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackIgnorePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recoveryGroupsGroupIdJobsJobIdRollbackIgnorePostRaw(requestParameters, initOverrides);
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 (재해복구)
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackMigrationPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackMigrationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackMigrationPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackMigrationPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/rollback/migration`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 (재해복구)
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackMigrationPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackMigrationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdRollbackMigrationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 재시도
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackRetryPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackRetryPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackRetryPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/rollback/retry`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 재시도
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackRetryPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdRollbackRetryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 (모의훈련)
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackSimulationPostRaw(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackSimulationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdDelete200Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackSimulationPost.');
        }

        if (requestParameters.job_id === null || requestParameters.job_id === undefined) {
            throw new runtime.RequiredError('job_id','Required parameter requestParameters.job_id was null or undefined when calling recoveryGroupsGroupIdJobsJobIdRollbackSimulationPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs/{job_id}/rollback/simulation`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))).replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters.job_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 롤백 (모의훈련)
     */
    async recoveryGroupsGroupIdJobsJobIdRollbackSimulationPost(requestParameters: RecoveryGroupsGroupIdJobsJobIdRollbackSimulationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdDelete200Response> {
        const response = await this.recoveryGroupsGroupIdJobsJobIdRollbackSimulationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 설명추가
     * 재해복구작업 생성
     */
    async recoveryGroupsGroupIdJobsPostRaw(requestParameters: RecoveryGroupsGroupIdJobsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGroupsGroupIdJobsPost201Response>> {
        if (requestParameters.group_id === null || requestParameters.group_id === undefined) {
            throw new runtime.RequiredError('group_id','Required parameter requestParameters.group_id was null or undefined when calling recoveryGroupsGroupIdJobsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/recovery/groups/{group_id}/jobs`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters.group_id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecoveryGroupsGroupIdJobsPostRequestToJSON(requestParameters.recovery_groups_group_id_jobs_post_request),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGroupsGroupIdJobsPost201ResponseFromJSON(jsonValue));
    }

    /**
     * 설명추가
     * 재해복구작업 생성
     */
    async recoveryGroupsGroupIdJobsPost(requestParameters: RecoveryGroupsGroupIdJobsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGroupsGroupIdJobsPost201Response> {
        const response = await this.recoveryGroupsGroupIdJobsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const RecoveryGroupsGroupIdJobsGetTypeEnum = {
    simulation: 'dr.recovery.type.simulation',
    migration: 'dr.recovery.type.migration'
} as const;
export type RecoveryGroupsGroupIdJobsGetTypeEnum = typeof RecoveryGroupsGroupIdJobsGetTypeEnum[keyof typeof RecoveryGroupsGroupIdJobsGetTypeEnum];
